// src/config/brands.js
export const brands = {
  "Phones & Tablets": [
    // Apple
    "Apple",
    
    // Samsung
    "Samsung",
    
    // Chinese Brands
    "Huawei",
    "Xiaomi",
    "OnePlus",
    "Oppo",
    "Vivo",
    "Realme",
    "Honor",
    "ZTE",
    "Meizu",
    "Coolpad",
    "Redmi",
    "POCO",
    "Nubia",
    "Lenovo",
    "TCL",
    "Hisense",
    
    // American Brands
    "Google",
    "Motorola",
    "Apple iPad",
    "Amazon Fire",
    "BLU",
    "Cat Phones",
    "Essential",
    
    // European Brands
    "Nokia",
    "Fairphone",
    "Wiko",
    "BQ",
    "Alcatel",
    
    // Japanese & Korean Brands
    "Sony",
    "LG",
    "Sharp",
    "Panasonic",
    "Kyocera",
    
    // African Market Brands
    "Tecno",
    "Infinix",
    "Itel",
    "Oraimo",
    "Safaricom Neon",
    
    // Gaming Phones
    "Razer",
    "ASUS ROG",
    "Black Shark",
    "Red Magic",
    "Lenovo Legion",
    
    // Rugged Phones
    "Doogee",
    "Ulefone",
    "Blackview",
    "Oukitel",
    "AGM",
    "Sonim",
    
    // Tablets Only
    "Microsoft Surface",
    "Huawei MatePad",
    "Lenovo Tab",
    "Samsung Galaxy Tab",
    "Xiaomi Pad",
    "Realme Pad",
    "Oppo Pad",
    "Amazon Kindle",
    "Barnes & Noble Nook",
    
    // Legacy Brands
    "HTC",
    "BlackBerry",
    "Palm",
    "LeEco",
    "Gionee",
    
    // Other
    "Other"
  ],

  "Vehicles": [
    // Japanese
    "Toyota",
    "Honda",
    "Nissan",
    "Mazda",
    "Subaru",
    "Mitsubishi",
    "Suzuki",
    "Lexus",
    "Infiniti",
    "Acura",
    "Daihatsu",
    "Isuzu",
    "Hino",
    
    // German
    "BMW",
    "Mercedes-Benz",
    "Volkswagen",
    "Audi",
    "Porsche",
    "Opel",
    "Mini",
    "Smart",
    
    // American
    "Ford",
    "Chevrolet",
    "GMC",
    "Jeep",
    "Dodge",
    "Chrysler",
    "Cadillac",
    "Lincoln",
    "Buick",
    "Tesla",
    "Rivian",
    "Lucid",
    "Hummer",
    
    // Korean
    "Hyundai",
    "Kia",
    "Genesis",
    "SsangYong",
    "Daewoo",
    
    // British
    "Land Rover",
    "Range Rover",
    "Jaguar",
    "Bentley",
    "Rolls Royce",
    "Aston Martin",
    "McLaren",
    "Lotus",
    "MG",
    "Vauxhall",
    
    // Italian
    "Ferrari",
    "Lamborghini",
    "Maserati",
    "Alfa Romeo",
    "Fiat",
    "Lancia",
    "Pagani",
    "Bugatti",
    
    // French
    "Peugeot",
    "Renault",
    "Citroën",
    "DS Automobiles",
    "Alpine",
    
    // Swedish
    "Volvo",
    "Saab",
    "Koenigsegg",
    "Polestar",
    
    // Chinese
    "BYD",
    "Geely",
    "Chery",
    "Great Wall",
    "Haval",
    "NIO",
    "XPeng",
    "Li Auto",
    "Wuling",
    "JAC",
    "Foton",
    "Dongfeng",
    "FAW",
    "BAIC",
    "Changan",
    "GAC",
    "Lynk & Co",
    "Zeekr",
    
    // Indian
    "Tata",
    "Mahindra",
    "Maruti Suzuki",
    "Force Motors",
    "Ashok Leyland",
    "Bajaj",
    "TVS",
    "Hero",
    
    // Czech
    "Skoda",
    
    // Spanish
    "SEAT",
    "Cupra",
    
    // Romanian
    "Dacia",
    
    // Russian
    "Lada",
    "UAZ",
    
    // Malaysian
    "Proton",
    "Perodua",
    
    // Motorcycles
    "Harley-Davidson",
    "Yamaha",
    "Kawasaki",
    "Honda Motorcycle",
    "Suzuki Motorcycle",
    "Ducati",
    "BMW Motorrad",
    "Triumph",
    "KTM",
    "Royal Enfield",
    "Vespa",
    "Piaggio",
    "Aprilia",
    
    // Trucks & Commercial
    "Scania",
    "Volvo Trucks",
    "MAN",
    "DAF",
    "Iveco",
    "Kenworth",
    "Peterbilt",
    "Freightliner",
    "Mack",
    "Western Star",
    "UD Trucks",
    "Fuso",
    
    // Other
    "Other"
  ],

  "Computers & Laptops": [
    // American
    "Apple",
    "Dell",
    "HP",
    "Microsoft",
    "IBM",
    "Gateway",
    "Alienware",
    "Corsair",
    "EVGA",
    "Intel",
    "NVIDIA",
    "AMD",
    
    // Chinese
    "Lenovo",
    "Huawei",
    "Xiaomi",
    "Honor",
    "Chuwi",
    "Teclast",
    "Jumper",
    
    // Taiwanese
    "Asus",
    "Acer",
    "MSI",
    "Gigabyte",
    "ASUS ROG",
    "ASUS TUF",
    "ASUS ZenBook",
    "ASUS VivoBook",
    "Aorus",
    "BenQ",
    
    // Japanese
    "Toshiba",
    "Fujitsu",
    "Panasonic",
    "Sony VAIO",
    "NEC",
    "Sharp",
    
    // Korean
    "Samsung",
    "LG",
    
    // European
    "Razer",
    "Medion",
    "Packard Bell",
    
    // Gaming Specific
    "Razer Blade",
    "MSI Gaming",
    "Alienware",
    "ASUS ROG",
    "Acer Predator",
    "HP Omen",
    "Lenovo Legion",
    
    // Workstation Brands
    "Dell Precision",
    "HP ZBook",
    "Lenovo ThinkPad",
    "Lenovo ThinkStation",
    
    // Chromebook Brands
    "Google Chromebook",
    "Samsung Chromebook",
    "HP Chromebook",
    "Acer Chromebook",
    "Lenovo Chromebook",
    "ASUS Chromebook",
    
    // Components (for custom builds)
    "Intel",
    "AMD",
    "NVIDIA",
    "Corsair",
    "G.Skill",
    "Kingston",
    "Crucial",
    "Western Digital",
    "Seagate",
    "Samsung SSD",
    "Sabrent",
    "NZXT",
    "Cooler Master",
    "Thermaltake",
    "be quiet!",
    "Fractal Design",
    "Lian Li",
    
    // Other
    "Other"
  ],

  "Gaming": [
    // Console Manufacturers
    "Sony PlayStation",
    "Microsoft Xbox",
    "Nintendo",
    "Sega",
    "Atari",
    "Valve (Steam Deck)",
    "Analogue",
    
    // Gaming Peripherals
    "Razer",
    "Logitech",
    "Logitech G",
    "SteelSeries",
    "Corsair",
    "HyperX",
    "ASUS ROG",
    "MSI",
    "Alienware",
    "Turtle Beach",
    "Astro Gaming",
    "Roccat",
    "Mad Catz",
    "SCUF Gaming",
    "Thrustmaster",
    "Hori",
    "8BitDo",
    "PowerA",
    "PDP",
    "Nacon",
    "Victrix",
    
    // Gaming Chairs
    "Secretlab",
    "DXRacer",
    "Noblechairs",
    "AKRacing",
    "GT Racing",
    "Respawn",
    "Cougar",
    "Vertagear",
    "AndaSeat",
    
    // VR Headsets
    "Meta (Oculus)",
    "HTC Vive",
    "Valve Index",
    "PlayStation VR",
    "HP Reverb",
    "Pimax",
    "Pico",
    
    // Streaming Gear
    "Elgato",
    "AVerMedia",
    "Blue Microphones",
    "Shure",
    "Rode",
    "Audio-Technica",
    "Focusrite",
    "GoXLR",
    
    // Gaming Monitors
    "ASUS ROG",
    "MSI Optix",
    "Acer Predator",
    "Samsung Odyssey",
    "LG UltraGear",
    "BenQ Zowie",
    "Alienware",
    "AOC Gaming",
    "ViewSonic",
    "Gigabyte Aorus",
    
    // Other
    "Other"
  ],

  "Electronics": [
    // TV Brands
    "Sony",
    "LG",
    "Samsung",
    "Panasonic",
    "Philips",
    "Sharp",
    "Toshiba",
    "Hisense",
    "TCL",
    "Vizio",
    "Skyworth",
    "Haier",
    "Insignia",
    "Element",
    "Westinghouse",
    "Sanyo",
    "JVC",
    "Magnavox",
    "RCA",
    
    // Audio Brands
    "Bose",
    "JBL",
    "Sony",
    "Sonos",
    "Harman Kardon",
    "Bang & Olufsen",
    "Denon",
    "Pioneer",
    "Yamaha",
    "Onkyo",
    "Marantz",
    "Marshall",
    "Klipsch",
    "KEF",
    "Bower & Wilkins",
    "Sennheiser",
    "Audio-Technica",
    "Shure",
    "AKG",
    "Beats by Dre",
    "Skullcandy",
    "Jabra",
    "Anker Soundcore",
    "Ultimate Ears",
    "Edifier",
    "Creative",
    "Cambridge Audio",
    "NAD Electronics",
    "McIntosh",
    
    // Camera Brands
    "Canon",
    "Nikon",
    "Sony",
    "Fujifilm",
    "Panasonic Lumix",
    "Olympus",
    "Leica",
    "Pentax",
    "Hasselblad",
    "GoPro",
    "DJI",
    "Insta360",
    "Ricoh",
    "Sigma",
    "Tamron",
    "Samyang",
    "Blackmagic",
    "RED",
    "ARRI",
    
    // Projectors
    "Epson",
    "BenQ",
    "Optoma",
    "LG",
    "Sony",
    "ViewSonic",
    "Anker Nebula",
    "XGIMI",
    "JMGO",
    "Vivitek",
    
    // Printers & Scanners
    "HP",
    "Canon",
    "Epson",
    "Brother",
    "Xerox",
    "Lexmark",
    "Ricoh",
    "Kyocera",
    "OKI",
    "Fujitsu",
    
    // Smart Home
    "Amazon (Alexa)",
    "Google (Nest)",
    "Apple (HomeKit)",
    "Ring",
    "Philips Hue",
    "TP-Link (Kasa)",
    "Wyze",
    "Arlo",
    "Ecobee",
    "Honeywell",
    "August",
    "SimpliSafe",
    "Eufy",
    "Nanoleaf",
    "LIFX",
    "Sengled",
    
    // Networking
    "TP-Link",
    "Netgear",
    "Asus",
    "Linksys",
    "D-Link",
    "Ubiquiti",
    "Cisco",
    "Huawei",
    "MikroTik",
    "Synology",
    "QNAP",
    "Buffalo",
    "Eero",
    "Google WiFi",
    "Orbi (Netgear)",
    
    // Other
    "Other"
  ],

  "Home, Furniture & Appliances": [
    // Furniture
    "IKEA",
    "Ashley Furniture",
    "La-Z-Boy",
    "Pottery Barn",
    "West Elm",
    "Crate & Barrel",
    "Restoration Hardware",
    "Wayfair",
    "Herman Miller",
    "Steelcase",
    "HON",
    "Sauder",
    "Walker Edison",
    "Zinus",
    "Casper",
    "Purple",
    "Tempur-Pedic",
    "Sealy",
    "Simmons",
    "Serta",
    "Nectar",
    "Sleep Number",
    
    // Kitchen Appliances
    "Philips",
    "Samsung",
    "LG",
    "Bosch",
    "Whirlpool",
    "KitchenAid",
    "Hisense",
    "Haier",
    "Midea",
    "Electrolux",
    "Miele",
    "Siemens",
    "AEG",
    "Beko",
    "Hotpoint",
    "Indesit",
    "Zanussi",
    "GE Appliances",
    "Frigidaire",
    "Maytag",
    "Kenmore",
    "Amana",
    "Sub-Zero",
    "Viking",
    "Wolf",
    "Thermador",
    "JennAir",
    "Smeg",
    "Fisher & Paykel",
    "Speed Queen",
    
    // Small Kitchen Appliances
    "Breville",
    "Cuisinart",
    "Kenwood",
    "Tefal",
    "Russell Hobbs",
    "Morphy Richards",
    "De'Longhi",
    "Nespresso",
    "Keurig",
    "Ninja",
    "Instant Pot",
    "Vitamix",
    "Blendtec",
    "Hamilton Beach",
    "Black & Decker",
    "Oster",
    "Sunbeam",
    "Proctor Silex",
    "Crock-Pot",
    "George Foreman",
    "Nutribullet",
    "Magic Bullet",
    "SMEG",
    "Dualit",
    "Sage",
    
    // Cleaning Appliances
    "Dyson",
    "Bissell",
    "Hoover",
    "Shark",
    "Roomba (iRobot)",
    "Ecovacs",
    "Roborock",
    "Eufy",
    "Neato",
    "Tineco",
    "Karcher",
    "Miele",
    "Electrolux",
    "Kenmore",
    "Dirt Devil",
    "Oreck",
    
    // Air Conditioning & Heating
    "Daikin",
    "Mitsubishi Electric",
    "LG",
    "Samsung",
    "Carrier",
    "Trane",
    "Lennox",
    "York",
    "Rheem",
    "Goodman",
    "Fujitsu",
    "Panasonic",
    "Gree",
    "Haier",
    "Hisense",
    "Midea",
    "Dyson",
    "Honeywell",
    "Delonghi",
    
    // Water Heaters
    "Rheem",
    "A.O. Smith",
    "Bradford White",
    "Rinnai",
    "Noritz",
    "Takagi",
    "Bosch",
    "Stiebel Eltron",
    "EcoSmart",
    
    // Other
    "Other"
  ],

  "Fashion": [
    // Sportswear
    "Nike",
    "Adidas",
    "Puma",
    "Reebok",
    "New Balance",
    "Under Armour",
    "Asics",
    "Fila",
    "Champion",
    "Kappa",
    "Umbro",
    "Lotto",
    "Skechers",
    "Brooks",
    "Saucony",
    "Mizuno",
    "Hoka One One",
    "On Running",
    
    // Casual Footwear
    "Converse",
    "Vans",
    "Dr. Martens",
    "Timberland",
    "Clarks",
    "Ecco",
    "Birkenstock",
    "Crocs",
    "Toms",
    "Sperry",
    "Cole Haan",
    "Steve Madden",
    
    // Luxury Brands
    "Gucci",
    "Louis Vuitton",
    "Prada",
    "Chanel",
    "Hermès",
    "Burberry",
    "Versace",
    "Dior",
    "Fendi",
    "Balenciaga",
    "Saint Laurent",
    "Givenchy",
    "Bottega Veneta",
    "Valentino",
    "Alexander McQueen",
    "Celine",
    "Loewe",
    "Off-White",
    "Balmain",
    "Moncler",
    "Canada Goose",
    "Stone Island",
    "Acne Studios",
    "Maison Margiela",
    "Rick Owens",
    "Yeezy",
    "Fear of God",
    "Palm Angels",
    "Kenzo",
    "Moschino",
    "Dolce & Gabbana",
    "Armani",
    "Ermenegildo Zegna",
    "Salvatore Ferragamo",
    "Tod's",
    "Brunello Cucinelli",
    
    // Premium Brands
    "Tommy Hilfiger",
    "Ralph Lauren",
    "Calvin Klein",
    "Lacoste",
    "Hugo Boss",
    "Diesel",
    "True Religion",
    "7 For All Mankind",
    "AG Jeans",
    "Citizens of Humanity",
    "Paige",
    "Frame",
    "Rag & Bone",
    "All Saints",
    "Ted Baker",
    "Paul Smith",
    "Kenzo",
    "Vivienne Westwood",
    "MCM",
    "Coach",
    "Kate Spade",
    "Michael Kors",
    "Marc Jacobs",
    "Tory Burch",
    
    // Fast Fashion
    "Zara",
    "H&M",
    "Uniqlo",
    "Gap",
    "Forever 21",
    "Mango",
    "Topshop",
    "Primark",
    "Pull & Bear",
    "Bershka",
    "Stradivarius",
    "Massimo Dutti",
    "Cos",
    "& Other Stories",
    "Monki",
    "Weekday",
    "ASOS",
    "Boohoo",
    "Pretty Little Thing",
    "Missguided",
    "Fashion Nova",
    "Shein",
    "Romwe",
    "Nasty Gal",
    "Urban Outfitters",
    "Free People",
    "Anthropologie",
    "Express",
    "American Eagle",
    "Abercrombie & Fitch",
    "Hollister",
    
    // Denim
    "Levi's",
    "Wrangler",
    "Lee",
    "Guess",
    "G-Star Raw",
    "Pepe Jeans",
    "Replay",
    "Nudie Jeans",
    "Edwin",
    "Carhartt",
    "Dickies",
    
    // Outdoor & Workwear
    "The North Face",
    "Patagonia",
    "Columbia",
    "Arc'teryx",
    "Fjällräven",
    "Barbour",
    "Hunter",
    "Timberland",
    "Carhartt WIP",
    "Dickies",
    
    // Underwear & Loungewear
    "Victoria's Secret",
    "Calvin Klein",
    "Tommy Hilfiger",
    "Hanes",
    "Fruit of the Loom",
    "Jockey",
    "Bonds",
    "Savage X Fenty",
    "Skims",
    "Spanx",
    
    // African Brands
    "Maxhosa",
    "Orange Culture",
    "Lisa Folawiyo",
    "Maki Oh",
    "Thebe Magugu",
    "Rich Mnisi",
    "Christie Brown",
    "Studio 189",
    
    // Other
    "Other"
  ],

  "Beauty & Personal Care": [
    // Makeup - Luxury
    "MAC Cosmetics",
    "Estée Lauder",
    "Lancôme",
    "Clinique",
    "NARS",
    "Bobbi Brown",
    "Urban Decay",
    "Too Faced",
    "Charlotte Tilbury",
    "Pat McGrath Labs",
    "Hourglass",
    "Laura Mercier",
    "Giorgio Armani Beauty",
    "Chanel Beauty",
    "Dior Beauty",
    "YSL Beauty",
    "Guerlain",
    "Tom Ford Beauty",
    "Givenchy Beauty",
    
    // Makeup - Affordable
    "Maybelline",
    "L'Oreal Paris",
    "Revlon",
    "NYX",
    "e.l.f.",
    "Milani",
    "Wet n Wild",
    "ColourPop",
    "Morphe",
    "BH Cosmetics",
    "Essence",
    "Catrice",
    "CoverGirl",
    "Rimmel",
    "Max Factor",
    "Almay",
    "Physician's Formula",
    
    // Makeup - Indie/Clean
    "Fenty Beauty",
    "Rare Beauty",
    "ILIA",
    "Tower 28",
    "Kosas",
    "Merit",
    "Saie",
    "Rose Inc",
    "Jones Road",
    "Westman Atelier",
    "Kjaer Weis",
    "RMS Beauty",
    "Tarte",
    "Benefit Cosmetics",
    "Becca",
    "IT Cosmetics",
    
    // Skincare - Luxury
    "La Mer",
    "SK-II",
    "Sisley",
    "La Prairie",
    "Augustinus Bader",
    "Tatcha",
    "Sunday Riley",
    "Drunk Elephant",
    "Fresh",
    "Kiehl's",
    "Origins",
    
    // Skincare - Clinical
    "The Ordinary",
    "Paula's Choice",
    "CeraVe",
    "Cetaphil",
    "La Roche-Posay",
    "Vichy",
    "Avène",
    "Bioderma",
    "Eucerin",
    "Neutrogena",
    "Differin",
    "SkinCeuticals",
    "Murad",
    "Peter Thomas Roth",
    "Dr. Dennis Gross",
    "Dermalogica",
    "Obagi",
    "iS Clinical",
    
    // Skincare - K-Beauty
    "Innisfree",
    "Laneige",
    "Sulwhasoo",
    "COSRX",
    "Klairs",
    "Some By Mi",
    "Beauty of Joseon",
    "Missha",
    "Etude House",
    "Banila Co",
    "Pyunkang Yul",
    "Benton",
    "Purito",
    "Neogen",
    "Dr. Jart+",
    "AmorePacific",
    
    // Skincare - J-Beauty
    "Shiseido",
    "Hada Labo",
    "Kose",
    "DHC",
    "Kanebo",
    "KOSE Sekkisei",
    
    // Haircare
    "L'Oreal",
    "Garnier",
    "Pantene",
    "Head & Shoulders",
    "Dove",
    "Herbal Essences",
    "TRESemmé",
    "Aussie",
    "Schwarzkopf",
    "Wella",
    "Redken",
    "Matrix",
    "Biolage",
    "Olaplex",
    "Oribe",
    "Moroccanoil",
    "Kerastase",
    "Bumble and Bumble",
    "Living Proof",
    "Aveda",
    "Paul Mitchell",
    "CHI",
    "Kenra",
    "Joico",
    "Sebastian Professional",
    "AG Hair",
    "DevaCurl",
    "SheaMoisture",
    "Cantu",
    "Mielle Organics",
    "OGX",
    "Not Your Mother's",
    "Briogeo",
    
    // Body Care
    "Nivea",
    "Dove",
    "Aveeno",
    "Vaseline",
    "Jergens",
    "Lubriderm",
    "Bath & Body Works",
    "The Body Shop",
    "Lush",
    "Sol de Janeiro",
    "Necessaire",
    "Ouai",
    
    // Fragrances
    "Chanel",
    "Dior",
    "Tom Ford",
    "Creed",
    "Jo Malone",
    "Le Labo",
    "Byredo",
    "Diptyque",
    "Maison Margiela Replica",
    "Versace",
    "Dolce & Gabbana",
    "Giorgio Armani",
    "Yves Saint Laurent",
    "Prada",
    "Gucci",
    "Burberry",
    "Calvin Klein",
    "Hugo Boss",
    "Ralph Lauren",
    "Marc Jacobs",
    "Viktor & Rolf",
    
    // Men's Grooming
    "Gillette",
    "Braun",
    "Philips",
    "Harry's",
    "Dollar Shave Club",
    "Jack Black",
    "Baxter of California",
    "Kiehl's Men",
    "Bulldog Skincare",
    "Clinique for Men",
    "Lab Series",
    "American Crew",
    "Crew",
    "Duke Cannon",
    "Every Man Jack",
    
    // Oral Care
    "Colgate",
    "Oral-B",
    "Sensodyne",
    "Crest",
    "Listerine",
    "Aquafresh",
    "Arm & Hammer",
    "Philips Sonicare",
    "Waterpik",
    
    // Other
    "Other"
  ],

  "Babies & Kids": [
    // Baby Gear
    "Fisher-Price",
    "Chicco",
    "Graco",
    "BabyBjorn",
    "Ergobaby",
    "Tula",
    "LÍLLÉbaby",
    "Baby K'tan",
    "Moby",
    "Boba",
    "Infantino",
    "Skip Hop",
    "Inglesina",
    "4moms",
    "Snuggle Me",
    "DockATot",
    "Boppy",
    "Baby Brezza",
    
    // Strollers & Car Seats
    "Bugaboo",
    "UPPAbaby",
    "Silver Cross",
    "Stokke",
    "Nuna",
    "Cybex",
    "Britax",
    "Maxi-Cosi",
    "Joie",
    "Baby Jogger",
    "BOB",
    "Thule",
    "Babyzen",
    "Quinny",
    "iCandy",
    "Mamas & Papas",
    "Cosatto",
    "Maclaren",
    "Mountain Buggy",
    "Phil & Teds",
    "Doona",
    "Evenflo",
    "Safety 1st",
    "Diono",
    "Clek",
    "Peg Perego",
    
    // Baby Feeding
    "Tommee Tippee",
    "Avent (Philips)",
    "Dr. Brown's",
    "MAM",
    "Comotomo",
    "Nanobébé",
    "Medela",
    "Spectra",
    "Elvie",
    "Willow",
    "Haakaa",
    "Lansinoh",
    "Nuby",
    "Munchkin",
    "OXO Tot",
    "Bumkins",
    "BabyBjorn",
    "Stokke Tripp Trapp",
    "Béaba",
    "Baby Bullet",
    
    // Diapers & Bath
    "Pampers",
    "Huggies",
    "Luvs",
    "Honest Company",
    "Seventh Generation",
    "Babyganics",
    "Hello Bello",
    "Coterie",
    "Kudos",
    "Earth's Best",
    "Bamboo Nature",
    "Naty",
    "Johnson & Johnson",
    "Aveeno Baby",
    "Cetaphil Baby",
    "Mustela",
    "Burt's Bees Baby",
    "California Baby",
    "Pipette",
    "Tubby Todd",
    "Puracy",
    
    // Baby Furniture
    "Crib (Delta Children)",
    "Babyletto",
    "DaVinci",
    "Graco",
    "Storkcraft",
    "Dream On Me",
    "Pottery Barn Kids",
    "Restoration Hardware Baby",
    "SNOO (Happiest Baby)",
    "Halo",
    "Bassinets",
    
    // Kids Toys (Overlap with Toys & Games)
    "LEGO",
    "Fisher-Price",
    "VTech",
    "LeapFrog",
    "Melissa & Doug",
    "Hape",
    "Plan Toys",
    "Fat Brain Toys",
    "B. Toys",
    "Manhattan Toy",
    "Janod",
    "Tender Leaf Toys",
    "Lovevery",
    
    // Kids Clothing
    "Carter's",
    "OshKosh B'gosh",
    "Gerber",
    "Hanna Andersson",
    "Primary",
    "Cat & Jack (Target)",
    "Old Navy Kids",
    "Gap Kids",
    "H&M Kids",
    "Zara Kids",
    "Mini Boden",
    "Tea Collection",
    "Petit Bateau",
    "Gymboree",
    "The Children's Place",
    "Janie and Jack",
    
    // Baby Monitors
    "Owlet",
    "Nanit",
    "Infant Optics",
    "VTech",
    "Eufy",
    "Motorola",
    "Arlo Baby",
    "HelloBaby",
    "Summer Infant",
    
    // Other
    "Other"
  ],

  "Toys & Games": [
    // Building Toys
    "LEGO",
    "LEGO Duplo",
    "LEGO Technic",
    "Mega Bloks",
    "K'NEX",
    "Meccano",
    "Magna-Tiles",
    "Tegu",
    "Lincoln Logs",
    "Playmobil",
    
    // Action Figures & Dolls
    "Mattel",
    "Barbie",
    "Hot Wheels",
    "Matchbox",
    "Hasbro",
    "Transformers",
    "G.I. Joe",
    "My Little Pony",
    "LOL Surprise",
    "American Girl",
    "Our Generation",
    "Baby Alive",
    "Cabbage Patch Kids",
    "Bratz",
    "Monster High",
    "Rainbow High",
    "Funko Pop",
    "NECA",
    "McFarlane Toys",
    "Hot Toys",
    "Sideshow Collectibles",
    "Bandai",
    "Takara Tomy",
    "Schleich",
    "Safari Ltd",
    "Papo",
    "Breyer",
    
    // Board Games
    "Hasbro Gaming",
    "Monopoly",
    "Scrabble",
    "Risk",
    "Clue",
    "Trivial Pursuit",
    "Mattel Games",
    "UNO",
    "Ravensburger",
    "Asmodee",
    "Catan Studio",
    "Days of Wonder",
    "Fantasy Flight Games",
    "Z-Man Games",
    "Stonemaier Games",
    "Exploding Kittens",
    "Gamewright",
    
    // Outdoor Toys
    "Nerf",
    "Super Soaker",
    "Little Tikes",
    "Step2",
    "Radio Flyer",
    "Razor",
    "Schwinn",
    "Huffy",
    "Strider",
    "Woom",
    "Micro Kickboard",
    "Globber",
    "Y-Fliker",
    "Pogo",
    "Spikeball",
    
    // Creative & Arts
    "Crayola",
    "Play-Doh",
    "Kinetic Sand",
    "Melissa & Doug",
    "Alex Toys",
    "Creativity for Kids",
    "Perler",
    "Rainbow Loom",
    "Spirograph",
    "Lite Brite",
    "Etch A Sketch",
    
    // Electronic Toys
    "VTech",
    "LeapFrog",
    "Fisher-Price",
    "Tamagotchi",
    "Furby",
    "Hatchimals",
    "FurReal Friends",
    "Paw Patrol",
    "Bluey",
    "Cocomelon",
    "Baby Shark",
    "PJ Masks",
    "Peppa Pig",
    
    // Remote Control
    "Traxxas",
    "Team Associated",
    "Arrma",
    "Losi",
    "Redcat Racing",
    "Axial",
    "Tamiya",
    "Kyosho",
    "HPI Racing",
    
    // Puzzles
    "Ravensburger",
    "Buffalo Games",
    "White Mountain",
    "Springbok",
    "Cobble Hill",
    "Galison",
    "Mudpuppy",
    "Melissa & Doug",
    "Djeco",
    
    // Trading Cards
    "Pokémon",
    "Magic: The Gathering",
    "Yu-Gi-Oh!",
    "Topps",
    "Panini",
    
    // Other
    "Other"
  ],

  "Sports & Outdoors": [
    // Athletic Footwear & Apparel
    "Nike",
    "Adidas",
    "Puma",
    "Reebok",
    "Under Armour",
    "New Balance",
    "Asics",
    "Brooks",
    "Saucony",
    "Hoka One One",
    "On Running",
    "Salomon",
    "Merrell",
    "La Sportiva",
    "Altra",
    "Mizuno",
    "Fila",
    "Champion",
    "Lululemon",
    "Athleta",
    "Outdoor Voices",
    "Vuori",
    "Tracksmith",
    "2XU",
    "CEP",
    
    // Outdoor Clothing
    "The North Face",
    "Patagonia",
    "Columbia",
    "Arc'teryx",
    "Mammut",
    "Marmot",
    "Mountain Hardwear",
    "Black Diamond",
    "Fjällräven",
    "Jack Wolfskin",
    "Rab",
    "Outdoor Research",
    "Montbell",
    "REI Co-op",
    "Kuhl",
    "prAna",
    "Cotopaxi",
    "Eddie Bauer",
    "L.L. Bean",
    "Cabela's",
    "Bass Pro Shops",
    
    // Camping & Hiking
    "Coleman",
    "Osprey",
    "Gregory",
    "Deuter",
    "CamelBak",
    "Hydro Flask",
    "Nalgene",
    "Yeti",
    "Stanley",
    "MSR",
    "Jetboil",
    "Snow Peak",
    "Big Agnes",
    "Kelty",
    "Sea to Summit",
    "Therm-a-Rest",
    "ENO (Eagles Nest Outfitters)",
    "Helinox",
    "Black Diamond",
    "Petzl",
    "Princeton Tec",
    "Goal Zero",
    "BioLite",
    "Garmin",
    "Suunto",
    "Coros",
    
    // Cycling
    "Trek",
    "Specialized",
    "Giant",
    "Cannondale",
    "Scott",
    "Santa Cruz",
    "Yeti Cycles",
    "Cervélo",
    "Pinarello",
    "Bianchi",
    "Canyon",
    "BMC",
    "Orbea",
    "Kona",
    "Salsa",
    "Surly",
    "All-City",
    "Brompton",
    "Dahon",
    "Tern",
    "Rad Power Bikes",
    "VanMoof",
    "Cowboy",
    "Shimano",
    "SRAM",
    "Campagnolo",
    "Giro",
    "Bell",
    "POC",
    "Oakley",
    "100%",
    "Smith",
    
    // Tennis & Racquet Sports
    "Wilson",
    "Head",
    "Babolat",
    "Yonex",
    "Prince",
    "Tecnifibre",
    "Dunlop",
    "Volkl",
    "Gamma",
    
    // Golf
    "Titleist",
    "Callaway",
    "TaylorMade",
    "Ping",
    "Cobra",
    "Mizuno",
    "Cleveland",
    "Srixon",
    "Bridgestone",
    "Scotty Cameron",
    "Odyssey",
    "FootJoy",
    "Puma Golf",
    "Adidas Golf",
    "Nike Golf",
    "Under Armour Golf",
    "TravisMathew",
    "Peter Millar",
    
    // Water Sports
    "Speedo",
    "Arena",
    "TYR",
    "Aqua Sphere",
    "Rip Curl",
    "Billabong",
    "Quiksilver",
    "Roxy",
    "O'Neill",
    "Hurley",
    "Volcom",
    "Body Glove",
    "Cressi",
    "Mares",
    "Scubapro",
    "Suunto Dive",
    "Aqua Lung",
    
    // Winter Sports
    "Burton",
    "Rossignol",
    "Salomon",
    "Atomic",
    "K2",
    "Head",
    "Volkl",
    "Blizzard",
    "Nordica",
    "Fischer",
    "Dynastar",
    "Lib Tech",
    "Capita",
    "Jones",
    "Never Summer",
    "GNU",
    "Ride",
    "Flow",
    "Union",
    "Smith",
    "Giro",
    "Oakley",
    "Anon",
    "POC",
    "Bolle",
    "The North Face",
    "Spyder",
    "Obermeyer",
    "Helly Hansen",
    "Bogner",
    
    // Team Sports
    "Nike",
    "Adidas",
    "Under Armour",
    "Puma",
    "Spalding",
    "Wilson",
    "Rawlings",
    "Louisville Slugger",
    "Easton",
    "DeMarini",
    "Marucci",
    "Mizuno",
    "Franklin",
    "Riddell",
    "Schutt",
    "STX",
    "Warrior",
    "Bauer",
    "CCM",
    "Warrior Hockey",
    "True",
    "Graf",
    
    // Fitness Equipment
    "Bowflex",
    "NordicTrack",
    "Peloton",
    "Technogym",
    "Life Fitness",
    "Precor",
    "Matrix Fitness",
    "Cybex",
    "Hammer Strength",
    "Rogue Fitness",
    "Titan Fitness",
    "Rep Fitness",
    "Concept2",
    "WaterRower",
    "Hydrow",
    "AssaultBike",
    "Schwinn",
    "Sole",
    "Horizon Fitness",
    "ProForm",
    "Sunny Health & Fitness",
    "Marcy",
    "TRX",
    "BOSU",
    "TheraBand",
    "Trigger Point",
    "Hyperice",
    "Theragun",
    "Compex",
    "PowerBlock",
    "Bowflex SelectTech",
    "Yes4All",
    "CAP Barbell",
    "AmazonBasics Fitness",
    
    // Yoga & Pilates
    "Lululemon",
    "Manduka",
    "Liforme",
    "Jade Yoga",
    "Gaiam",
    "PrAna",
    "Alo Yoga",
    "Athleta",
    "Beyond Yoga",
    "Sweaty Betty",
    "Balanced Body",
    "Merrithew",
    
    // Other
    "Other"
  ],

  "Health & Fitness": [
    // Wearables & Trackers
    "Fitbit",
    "Garmin",
    "Apple Watch",
    "Samsung Galaxy Watch",
    "Whoop",
    "Polar",
    "Suunto",
    "Coros",
    "Amazfit",
    "Xiaomi Mi Band",
    "Oura",
    "Withings",
    
    // Home Gym Equipment
    "Bowflex",
    "NordicTrack",
    "Peloton",
    "Technogym",
    "Life Fitness",
    "Rogue Fitness",
    "Titan Fitness",
    "Rep Fitness",
    "Concept2",
    "Hydrow",
    "Tonal",
    "Mirror",
    "Tempo",
    "Schwinn",
    "ProForm",
    "Sole Fitness",
    "Horizon Fitness",
    "Assault Fitness",
    "TRX",
    "Bowflex SelectTech",
    "PowerBlock",
    "Ironmaster",
    
    // Recovery & Therapy
    "Theragun (Therabody)",
    "Hyperice",
    "Hypervolt",
    "TimTam",
    "Ekrin Athletics",
    "Bob and Brad",
    "Compex",
    "Marc Pro",
    "NormaTec",
    "RecoveryPump",
    "TriggerPoint",
    "Foam Rollers",
    "TENS Units",
    "Chirp",
    "Pso-Rite",
    
    // Health Monitoring
    "Omron",
    "Withings",
    "Braun",
    "iHealth",
    "QardioArm",
    "Renpho",
    "Etekcity",
    "Eufy Smart Scale",
    "Wyze Scale",
    "Tanita",
    "InBody",
    "FreeStyle Libre",
    "Dexcom",
    "OneTouch",
    "Accu-Chek",
    "ResMed",
    "Philips Respironics",
    
    // Supplements & Nutrition
    "Optimum Nutrition",
    "Myprotein",
    "BSN",
    "MuscleTech",
    "Dymatize",
    "Cellucor",
    "JYM Supplement Science",
    "Ghost",
    "Transparent Labs",
    "Legion Athletics",
    "Kaged Muscle",
    "Thorne",
    "Garden of Life",
    "Vital Proteins",
    "Athletic Greens",
    "Huel",
    "Soylent",
    "RXBAR",
    "Quest Nutrition",
    "Clif Bar",
    "Kind",
    "LÄRABAR",
    
    // Yoga & Mindfulness
    "Manduka",
    "Liforme",
    "Jade Yoga",
    "Gaiam",
    "Lululemon",
    "B Yoga",
    "Prana",
    "Calm (App)",
    "Headspace (App)",
    "Muse (Meditation Headband)",
    
    // Sportswear Brands
    "Nike",
    "Adidas",
    "Under Armour",
    "Lululemon",
    "Athleta",
    "Gymshark",
    "Outdoor Voices",
    "Vuori",
    "Rhone",
    "Ten Thousand",
    "Tracksmith",
    "2XU",
    "Virus",
    "Hylete",
    
    // Other
    "Other"
  ],

  "Musical Instruments": [
    // Pianos & Keyboards
    "Yamaha",
    "Roland",
    "Korg",
    "Casio",
    "Nord",
    "Kawai",
    "Steinway & Sons",
    "Bösendorfer",
    "Fazioli",
    "Bechstein",
    "Blüthner",
    "Mason & Hamlin",
    "Schimmel",
    "Estonia",
    "Grotrian-Steinweg",
    "Samick",
    "Young Chang",
    "Baldwin",
    "Artesia",
    "Alesis",
    "M-Audio",
    "Native Instruments",
    "Akai",
    "Novation",
    "Nektar",
    
    // Guitars (Acoustic & Electric)
    "Fender",
    "Gibson",
    "Martin",
    "Taylor",
    "Epiphone",
    "PRS (Paul Reed Smith)",
    "Ibanez",
    "ESP",
    "LTD",
    "Jackson",
    "Charvel",
    "Schecter",
    "Gretsch",
    "Rickenbacker",
    "Music Man (Ernie Ball)",
    "G&L",
    "Squier",
    "Yamaha",
    "Takamine",
    "Seagull",
    "Guild",
    "Alvarez",
    "Breedlove",
    "Larrivée",
    "Collings",
    "Santa Cruz",
    "Bourgeois",
    "Eastman",
    "Córdoba",
    "Ramirez",
    "Godin",
    "Reverend",
    "Dean",
    "B.C. Rich",
    "EVH",
    "Sterling by Music Man",
    "Harley Benton",
    "Cort",
    "Washburn",
    "Danelectro",
    "Hofner",
    "Hagstrom",
    "D'Angelico",
    "Heritage",
    "Suhr",
    "Tom Anderson",
    "Nash Guitars",
    "Fano",
    
    // Bass Guitars
    "Fender",
    "Music Man",
    "Warwick",
    "Ibanez",
    "Spector",
    "Rickenbacker",
    "Lakland",
    "G&L",
    "Dingwall",
    "Sandberg",
    "MTD",
    "Fodera",
    "Sadowsky",
    "Mayones",
    "NS Design",
    "Sire",
    "Sterling by Music Man",
    "Yamaha",
    "ESP",
    "Schecter",
    "Jackson",
    
    // Drums & Percussion
    "Pearl",
    "DW (Drum Workshop)",
    "Ludwig",
    "Tama",
    "Yamaha",
    "Gretsch Drums",
    "Sonor",
    "Mapex",
    "PDP (Pacific Drums)",
    "Ddrum",
    "Sakae",
    "Canopus",
    "British Drum Co",
    "SJC Custom Drums",
    "Craviotto",
    "Brady Drums",
    "Noble & Cooley",
    "Roland V-Drums",
    "Alesis",
    "Simmons",
    "2Box",
    "EFNOTE",
    "Zildjian",
    "Sabian",
    "Meinl",
    "Paiste",
    "Istanbul Agop",
    "Istanbul Mehmet",
    "Dream Cymbals",
    "Bosphorus",
    "UFIP",
    "Vic Firth",
    "Pro-Mark",
    "Vater",
    "Remo",
    "Evans",
    "Aquarian",
    
    // Orchestral Strings
    "Yamaha",
    "Stentor",
    "Cecilio",
    "Cremona",
    "Eastman",
    "Shen",
    "Scott Cao",
    "Jay Haide",
    "D Z Strad",
    "Knilling",
    "Karl Höfner",
    "Gewa",
    "Primavera",
    "Engelhardt",
    
    // Wind Instruments
    "Yamaha",
    "Buffet Crampon",
    "Selmer",
    "Conn-Selmer",
    "Bach",
    "Getzen",
    "Jupiter",
    "Gemeinhardt",
    "Pearl Flutes",
    "Muramatsu",
    "Powell",
    "Haynes",
    "Altus",
    "Sankyo",
    "Miyazawa",
    "Trevor James",
    "Yanagisawa",
    "Keilwerth",
    "P. Mauriat",
    "Cannonball",
    "Eastman Winds",
    "Holton",
    "King",
    "Blessing",
    "Schilke",
    "Kanstul",
    "Shires",
    "Edwards",
    "Yamaha",
    "Leblanc",
    "Backun",
    "Patricola",
    "Ridenour",
    "Uebel",
    "Wurlitzer",
    "Loree",
    "Fox",
    "Heckel",
    "Puchner",
    "Howarth",
    
    // Amps & Effects
    "Fender",
    "Marshall",
    "Vox",
    "Orange",
    "Mesa Boogie",
    "Peavey",
    "Line 6",
    "Boss",
    "Blackstar",
    "Hughes & Kettner",
    "Bogner",
    "Soldano",
    "Friedman",
    "Two-Rock",
    "Matchless",
    "Dr. Z",
    "Supro",
    "Kemper",
    "Fractal Audio",
    "Neural DSP",
    "HeadRush",
    "Positive Grid",
    "Strymon",
    "Eventide",
    "TC Electronic",
    "Electro-Harmonix",
    "MXR",
    "Dunlop",
    "Wampler",
    "JHS Pedals",
    "Walrus Audio",
    "Earthquaker Devices",
    "Chase Bliss Audio",
    "Meris",
    "Source Audio",
    "Empress Effects",
    "Darkglass",
    "Ampeg",
    "Gallien-Krueger",
    "Aguilar",
    "Markbass",
    "Hartke",
    "Eden",
    "SWR",
    "TC Electronic Bass",
    "EBS",
    
    // Pro Audio & Recording
    "Shure",
    "Sennheiser",
    "Audio-Technica",
    "AKG",
    "Rode",
    "Neumann",
    "Blue Microphones",
    "Beyerdynamic",
    "Electro-Voice",
    "DPA",
    "Schoeps",
    "Telefunken",
    "Mojave Audio",
    "Warm Audio",
    "Universal Audio",
    "Focusrite",
    "PreSonus",
    "Behringer",
    "Mackie",
    "Allen & Heath",
    "Soundcraft",
    "Midas",
    "Yamaha",
    "Roland",
    "TASCAM",
    "Zoom",
    "Apogee",
    "RME",
    "Audient",
    "SSL",
    "API",
    "Neve",
    "Chandler Limited",
    "BAE Audio",
    "Avalon",
    "Manley",
    "Rupert Neve Designs",
    "Grace Design",
    "Genelec",
    "Adam Audio",
    "Focal",
    "KRK",
    "JBL Professional",
    "Yamaha HS Series",
    "Dynaudio",
    "PMC",
    "Barefoot Sound",
    "Amphion",
    "Neumann Monitors",
    "ATC",
    "EVE Audio",
    "IK Multimedia",
    "Kali Audio",
    "PreSonus Eris",
    
    // DJ Equipment
    "Pioneer DJ",
    "Denon DJ",
    "Numark",
    "Native Instruments",
    "Rane",
    "Allen & Heath Xone",
    "Technics",
    "Reloop",
    "Hercules",
    "Roland DJ",
    
    // Other
    "Other"
  ],

  "Books & Stationery": [
    // Major Publishers
    "Penguin Random House",
    "HarperCollins",
    "Simon & Schuster",
    "Hachette",
    "Macmillan",
    "Scholastic",
    "Wiley",
    "Pearson",
    "McGraw-Hill",
    "Oxford University Press",
    "Cambridge University Press",
    "Springer",
    "Elsevier",
    "Thomson Reuters",
    "Cengage",
    "DK Publishing",
    "National Geographic",
    "Lonely Planet",
    "Fodor's",
    "Frommer's",
    "Rough Guides",
    "Taschen",
    "Phaidon",
    "Rizzoli",
    "Chronicle Books",
    "Workman Publishing",
    "Bloomsbury",
    "Faber & Faber",
    "Vintage",
    "Anchor Books",
    "Knopf",
    "Little, Brown",
    "Grand Central",
    "Atria",
    "Gallery Books",
    "Scribner",
    
    // Writing Instruments
    "Parker",
    "Montblanc",
    "Cross",
    "Waterman",
    "Lamy",
    "Pilot",
    "Uni-ball",
    "Pentel",
    "Zebra",
    "Bic",
    "Sharpie",
    "Staedtler",
    "Faber-Castell",
    "Prismacolor",
    "Copic",
    "Sakura",
    "Tombow",
    "Rotring",
    "TWSBI",
    "Kaweco",
    "Diplomat",
    "Pelikan",
    "Visconti",
    "Aurora",
    "Caran d'Ache",
    "Sailor",
    "Platinum",
    "Namiki",
    "Esterbrook",
    "Narwhal",
    "Opus 88",
    "Conklin",
    "Edison Pen Co",
    
    // Notebooks & Paper
    "Moleskine",
    "Leuchtturm1917",
    "Rhodia",
    "Clairefontaine",
    "Field Notes",
    "Baron Fig",
    "Dingbats",
    "Archer & Olive",
    "Paperblanks",
    "Smythson",
    "Midori",
    "Traveler's Company",
    "Hobonichi",
    "Kokuyo",
    "Maruman",
    "Life Noble",
    "Tomoe River",
    "Mnemosyne",
    "Apica",
    "Muji",
    "Cambridge",
    "Five Star",
    "Mead",
    "Oxford (Hamelin)",
    "Black n' Red",
    "Pukka Pad",
    
    // Art Supplies
    "Winsor & Newton",
    "Daler-Rowney",
    "Liquitex",
    "Golden",
    "Daniel Smith",
    "Schmincke",
    "Holbein",
    "Sennelier",
    "M. Graham",
    "QoR",
    "Da Vinci",
    "Escoda",
    "Princeton Artist Brush",
    "Rosemary & Co",
    "Raphael",
    "Silver Brush",
    "Canson",
    "Strathmore",
    "Arches",
    "Fabriano",
    "Stonehenge",
    "Legion Paper",
    "Hahnemühle",
    "Saunders Waterford",
    "Blick",
    "Utrecht",
    "Gamblin",
    "Williamsburg",
    "Old Holland",
    "Michael Harding",
    
    // Office Supplies
    "3M (Post-it)",
    "Scotch",
    "Avery",
    "Fellowes",
    "Swingline",
    "Bostitch",
    "Acco",
    "Esselte",
    "Elmer's",
    "Gorilla Glue",
    "X-Acto",
    "Fiskars",
    "Westcott",
    "Staples",
    "Office Depot",
    
    // Planners & Organization
    "Erin Condren",
    "Happy Planner (Me & My Big Ideas)",
    "Plum Paper",
    "Passion Planner",
    "Clever Fox",
    "Panda Planner",
    "Productivity Planner",
    "Day Designer",
    "Emily Ley",
    "Filofax",
    "Franklin Covey",
    "At-A-Glance",
    "Blue Sky",
    
    // Other
    "Other"
  ],

  "Art & Collectibles": [
    // Art Supplies (See Books & Stationery for more)
    "Winsor & Newton",
    "Daler-Rowney",
    "Liquitex",
    "Golden",
    "Daniel Smith",
    "Faber-Castell",
    "Prismacolor",
    "Copic",
    "Canson",
    "Strathmore",
    
    // Collectible Figures
    "Funko",
    "Funko Pop",
    "Hot Toys",
    "Sideshow Collectibles",
    "NECA",
    "McFarlane Toys",
    "Kotobukiya",
    "Good Smile Company",
    "Bandai",
    "Tamashii Nations",
    "S.H.Figuarts",
    "Figma",
    "Nendoroid",
    "Medicom",
    "MAFEX",
    "Revoltech",
    "ThreeZero",
    "ThreeA",
    "Prime 1 Studio",
    "Queen Studios",
    "Iron Studios",
    "XM Studios",
    "Tsume Art",
    "First 4 Figures",
    "Gaming Heads",
    "Gecco",
    "Mondo",
    "Super7",
    "Mezco",
    "Marvel Legends",
    "Star Wars Black Series",
    "DC Multiverse",
    "Transformers Masterpiece",
    "Hasbro Pulse",
    
    // Trading Cards
    "Topps",
    "Panini",
    "Upper Deck",
    "Pokémon TCG",
    "Magic: The Gathering",
    "Yu-Gi-Oh!",
    "Sports Cards",
    "Baseball Cards",
    "Basketball Cards",
    "Football Cards",
    "Hockey Cards",
    "Bowman",
    "Prizm",
    "Select",
    "Donruss",
    "Optic",
    "Mosaic",
    
    // Coins & Stamps
    "US Mint",
    "Royal Mint",
    "Perth Mint",
    "Canadian Mint",
    "Austrian Mint",
    "PAMP Suisse",
    "Credit Suisse",
    "Engelhard",
    "Johnson Matthey",
    "American Gold Eagle",
    "American Silver Eagle",
    "Krugerrand",
    "Maple Leaf",
    "Philharmonic",
    "Britannia",
    "Chinese Panda",
    
    // Antiques
    "Antique Furniture",
    "Vintage China",
    "Crystal",
    "Silverware",
    "Porcelain",
    "Pottery",
    "Vintage Jewelry",
    "Estate Jewelry",
    "Vintage Watches",
    "Vintage Clocks",
    "Oil Paintings",
    "Watercolors",
    "Prints",
    "Lithographs",
    "Etchings",
    "Sculptures",
    "Bronzes",
    "Folk Art",
    "Primitive Art",
    "Asian Antiques",
    "African Art",
    "Pre-Columbian",
    "Native American",
    
    // Vintage & Retro
    "Vintage Toys",
    "Vintage Games",
    "Vintage Electronics",
    "Vintage Advertising",
    "Vintage Signs",
    "Vintage Posters",
    "Movie Memorabilia",
    "Music Memorabilia",
    "Sports Memorabilia",
    "Autographs",
    "Celebrity Items",
    "Historical Documents",
    "Maps",
    "Books (First Editions)",
    "Manuscripts",
    "Photographs",
    "Vintage Fashion",
    "Vintage Accessories",
    "Mid-Century Modern",
    "Art Deco",
    "Art Nouveau",
    "Victorian",
    "Edwardian",
    
    // Fine Art
    "Original Paintings",
    "Limited Edition Prints",
    "Giclée Prints",
    "Photography",
    "Digital Art",
    "Mixed Media",
    "Collage",
    "Assemblage",
    "Installation Art",
    "Sculpture",
    "Ceramics",
    "Glass Art",
    "Textile Art",
    "Fiber Art",
    "Jewelry Art",
    "Metal Art",
    "Wood Art",
    "Paper Art",
    "Street Art",
    "Graffiti Art",
    "Pop Art",
    "Contemporary Art",
    "Modern Art",
    "Abstract Art",
    "Impressionist",
    "Realist",
    "Surrealist",
    
    // Other
    "Other"
  ],

  "Pets": [
    // Pet Food - Dogs
    "Royal Canin",
    "Hill's Science Diet",
    "Purina Pro Plan",
    "Pedigree",
    "Iams",
    "Eukanuba",
    "Blue Buffalo",
    "Wellness",
    "Orijen",
    "Acana",
    "Merrick",
    "Canidae",
    "Taste of the Wild",
    "Nutro",
    "Natural Balance",
    "Rachael Ray Nutrish",
    "Diamond Naturals",
    "Fromm",
    "Zignature",
    "Instinct",
    "Nulo",
    "Open Farm",
    "Stella & Chewy's",
    "Primal",
    "The Honest Kitchen",
    "Nom Nom",
    "Ollie",
    "Farmer's Dog",
    "Just Food for Dogs",
    "Cesar",
    "Beneful",
    "Kibbles 'n Bits",
    "Alpo",
    
    // Pet Food - Cats
    "Royal Canin",
    "Hill's Science Diet",
    "Purina Pro Plan",
    "Whiskas",
    "Friskies",
    "Fancy Feast",
    "Sheba",
    "Meow Mix",
    "Iams",
    "Blue Buffalo",
    "Wellness",
    "Orijen Cat",
    "Instinct",
    "Nulo",
    "Tiki Cat",
    "Weruva",
    "Ziwi Peak",
    "Fussie Cat",
    "Applaws",
    
    // Pet Supplies & Accessories
    "Kong",
    "Nylabone",
    "Chuckit!",
    "Outward Hound",
    "Ruffwear",
    "Kurgo",
    "Sleepypod",
    "PetSafe",
    "Whistle",
    "Fi",
    "Furbo",
    "Petcube",
    "Catit",
    "SmartyKat",
    "Yeowww!",
    "Bergan",
    "Sherpa",
    "Midwest Homes for Pets",
    "Frisco",
    "Chewy",
    
    // Pet Beds & Furniture
    "K&H Pet Products",
    "Best Friends by Sheri",
    "FurHaven",
    "Big Barker",
    "Casper Dog Bed",
    "PetFusion",
    "Orvis",
    "LL Bean Dog Bed",
    "Molly Mutt",
    
    // Pet Health & Grooming
    "Frontline",
    "Advantage",
    "Seresto",
    "NexGard",
    "Bravecto",
    "Simparica",
    "Heartgard",
    "Sentinel",
    "Trifexis",
    "Revolution",
    "Apoquel",
    "Cosequin",
    "Dasuquin",
    "Nutramax",
    "VetriScience",
    "Zesty Paws",
    "Vet's Best",
    "TropiClean",
    "Earthbath",
    "Burt's Bees for Pets",
    "Nature's Miracle",
    "Rocco & Roxie",
    "Furminator",
    "Andis",
    "Wahl",
    "Oster",
    "Chris Christensen",
    "Safari",
    
    // Aquarium & Fish
    "Tetra",
    "API",
    "Fluval",
    "Marineland",
    "Penn-Plax",
    "Aqueon",
    "Seachem",
    "Hikari",
    "Omega One",
    "Eheim",
    "Aquaclear",
    "Hydor",
    "Cobalt Aquatics",
    "Red Sea",
    "Coral Life",
    
    // Birds
    "Kaytee",
    "ZuPreem",
    "Harrison's Bird Foods",
    "Roudybush",
    "Lafeber",
    "Prevue Pet Products",
    "Vision",
    "Ware Manufacturing",
    
    // Small Animals
    "Kaytee",
    "Oxbow",
    "Living World",
    "Carefresh",
    "Vitakraft",
    "Supreme Petfoods",
    "Higgins",
    
    // Reptiles
    "Zoo Med",
    "Exo Terra",
    "Zilla",
    "Fluker's",
    "Rep-Cal",
    "Repashy",
    "Pangea",
    
    // Other
    "Other"
  ],

  "Commercial Equipment & Tools": [
    // Power Tools
    "Bosch",
    "Makita",
    "DeWalt",
    "Milwaukee",
    "Hilti",
    "Festool",
    "Metabo",
    "Hitachi (Metabo HPT)",
    "Ryobi",
    "Ridgid",
    "Porter-Cable",
    "Black & Decker",
    "Craftsman",
    "Kobalt",
    "Skil",
    "Dremel",
    "Flex",
    "Fein",
    "Mafell",
    "Domino (Festool)",
    "SawStop",
    "Powermatic",
    "Jet",
    "Delta",
    "Grizzly",
    "Laguna Tools",
    "Rikon",
    "Shop Fox",
    "WEN",
    "Wen",
    "Harbor Freight (Bauer, Hercules)",
    
    // Hand Tools
    "Stanley",
    "Klein Tools",
    "Knipex",
    "Wera",
    "Wiha",
    "PB Swiss Tools",
    "Snap-on",
    "Mac Tools",
    "Matco",
    "Proto",
    "SK Hand Tools",
    "GearWrench",
    "Tekton",
    "Husky",
    "Craftsman",
    "Kobalt",
    "Irwin",
    "Crescent",
    "Channellock",
    "Estwing",
    "Stiletto",
    "Vaughan",
    "Marshalltown",
    "Bon Tool",
    "Goldblatt",
    
    // Outdoor Power Equipment
    "Stihl",
    "Husqvarna",
    "Echo",
    "Shindaiwa",
    "Redmax",
    "Makita Outdoor",
    "DeWalt Outdoor",
    "Milwaukee Outdoor",
    "Ego",
    "Greenworks",
    "Ryobi Outdoor",
    "Black & Decker Outdoor",
    "Toro",
    "Honda Power Equipment",
    "John Deere",
    "Cub Cadet",
    "Troy-Bilt",
    "Craftsman Outdoor",
    "Ariens",
    "Briggs & Stratton",
    "Kohler Engines",
    "Kawasaki Engines",
    
    // Welding
    "Lincoln Electric",
    "Miller Electric",
    "ESAB",
    "Hobart",
    "Fronius",
    "Hypertherm",
    "Thermal Dynamics",
    "Victor",
    "Forney",
    "Everlast",
    "YesWelder",
    "Eastwood",
    "Longevity",
    "AHP",
    "Titanium",
    
    // Compressors & Air Tools
    "Ingersoll Rand",
    "Chicago Pneumatic",
    "Snap-on Air Tools",
    "Matco Air Tools",
    "Campbell Hausfeld",
    "California Air Tools",
    "Quincy",
    "Sullair",
    "Kaeser",
    "Atlas Copco",
    "Rolair",
    "Makita Air",
    "Senco",
    "Bostitch Air",
    "Paslode",
    "Hitachi Air",
    
    // Cleaning Equipment
    "Kärcher",
    "Simpson",
    "Generac",
    "Sun Joe",
    "Greenworks",
    "Ryobi Pressure Washers",
    "Honda Pressure Washers",
    "Nilfisk",
    "Tennant",
    "Clarke",
    "Bissell Commercial",
    "Hoover Commercial",
    "ProTeam",
    "Sanitaire",
    "Windsor Kärcher",
    
    // Heavy Equipment
    "Caterpillar",
    "Komatsu",
    "John Deere",
    "Case",
    "Volvo Construction",
    "Hitachi Construction",
    "Kobelco",
    "JCB",
    "Bobcat",
    "Kubota",
    "New Holland Construction",
    "Takeuchi",
    "Yanmar",
    "Doosan",
    "Hyundai Construction",
    "XCMG",
    "Sany",
    "Liebherr",
    "Terex",
    "Manitou",
    "JLG",
    "Genie",
    "Skyjack",
    "Haulotte",
    
    // Generators
    "Generac",
    "Honda Generators",
    "Yamaha Generators",
    "Champion",
    "Westinghouse",
    "Briggs & Stratton",
    "Kohler Generators",
    "Cummins",
    "Cat Generators",
    "Onan",
    "DuroMax",
    "WEN Generators",
    "Pulsar",
    "A-iPower",
    "Firman",
    
    // Other
    "Other"
  ],

    "Repair & Construction": [
    // Power Tools
    "Bosch",
    "Makita",
    "DeWalt",
    "Milwaukee",
    "Hilti",
    "Festool",
    "Metabo",
    "Hitachi (Metabo HPT)",
    "Ryobi",
    "Ridgid",
    "Porter-Cable",
    "Black & Decker",
    "Craftsman",
    "Kobalt",
    "Skil",
    "Dremel",
    "Flex",
    "Fein",
    "Mafell",
    "SawStop",
    "WEN",
    "Harbor Freight",
    
    // Hand Tools
    "Stanley",
    "Klein Tools",
    "Knipex",
    "Wera",
    "Wiha",
    "Snap-on",
    "Mac Tools",
    "Matco",
    "Proto",
    "GearWrench",
    "Tekton",
    "Husky",
    "Craftsman",
    "Irwin",
    "Crescent",
    "Channellock",
    "Estwing",
    "Vaughan",
    "Marshalltown",
    "Goldblatt",
    
    // Measuring & Layout
    "Stanley FatMax",
    "Milwaukee Tape Measures",
    "DeWalt Measuring",
    "Stabila",
    "Kapro",
    "Empire Level",
    "Johnson Level",
    "Bosch Laser",
    "DeWalt Laser",
    "Leica Geosystems",
    "Topcon",
    "Trimble",
    "CST/berger",
    "Pacific Laser Systems",
    "Fluke",
    "Klein Multimeters",
    
    // Fasteners & Anchors
    "Simpson Strong-Tie",
    "Hilti Anchors",
    "Powers Fasteners",
    "Tapcon",
    "Ramset",
    "Red Head",
    "ITW Buildex",
    "Grip-Rite",
    "Senco Fasteners",
    "Paslode",
    "Bostitch Fasteners",
    "Hitachi Fasteners",
    "GRK Fasteners",
    "Spax",
    "Kreg",
    "Pocket Hole Systems",
    
    // Plumbing Tools & Supplies
    "Ridgid Plumbing",
    "Milwaukee Plumbing",
    "Rothenberger",
    "Reed Manufacturing",
    "General Pipe Cleaners",
    "Rigid (Emerson)",
    "Oatey",
    "Charlotte Pipe",
    "Nibco",
    "SharkBite",
    "Uponor",
    "Viega",
    "Watts",
    "Moen",
    "Delta Faucet",
    "Kohler",
    "American Standard",
    "Grohe",
    "Hansgrohe",
    "Pfister",
    "Symmons",
    "Sloan",
    "Zurn",
    "Gerber",
    "Toto",
    
    // Electrical Tools & Supplies
    "Klein Tools",
    "Fluke",
    "Ideal Industries",
    "Greenlee",
    "Southwire",
    "Milwaukee Electrical",
    "Knipex",
    "Wago",
    "Leviton",
    "Eaton",
    "Siemens",
    "Square D (Schneider)",
    "GE Electrical",
    "Lutron",
    "Legrand",
    "Hubbell",
    "Pass & Seymour",
    "Cooper",
    "ABB",
    "Carlon",
    
    // HVAC Tools & Equipment
    "Fieldpiece",
    "Testo",
    "Yellow Jacket",
    "Mastercool",
    "Robinair",
    "Navac",
    "Appion",
    "CPS Products",
    "Hilmor",
    "Malco",
    "Imperial",
    "JB Industries",
    "Inficon",
    "Supco",
    "Honeywell",
    "Emerson",
    "Danfoss",
    "Copeland",
    "Carrier",
    "Trane",
    "Lennox",
    "Rheem",
    "Goodman",
    "Daikin",
    "Mitsubishi Electric",
    "Fujitsu",
    "LG HVAC",
    "Samsung HVAC",
    
    // Concrete & Masonry
    "Quikrete",
    "Sakrete",
    "Rapid Set",
    "Bon Tool",
    "Marshalltown",
    "Kraft Tool",
    "QLT",
    "Goldblatt",
    "Stihl Concrete",
    "Husqvarna Concrete",
    "Hilti Concrete",
    "Makita Concrete",
    "Bosch Concrete",
    "DeWalt Concrete",
    "Wacker Neuson",
    "Multiquip",
    "Whiteman",
    "Stone",
    "Allen Engineering",
    "MBW",
    "Bartell",
    
    // Roofing
    "GAF",
    "Owens Corning",
    "CertainTeed",
    "Tamko",
    "Atlas Roofing",
    "IKO",
    "Malarkey",
    "Firestone Building Products",
    "Johns Manville",
    "Carlisle",
    "Versico",
    "Duro-Last",
    "Siplast",
    "Bostitch Roofing Nailers",
    "Hitachi Roofing",
    "Makita Roofing",
    "AJC Tools",
    "Malco Roofing",
    
    // Drywall & Plastering
    "USG",
    "National Gypsum",
    "Georgia-Pacific",
    "CertainTeed Gypsum",
    "Knauf",
    "American Gypsum",
    "Hamilton",
    "Marshalltown",
    "Goldblatt",
    "Kraft Tool",
    "Level5",
    "TapeTech",
    "Drywall Master",
    "Columbia Taping",
    "Northstar",
    "Blue Line USA",
    "CanAm Tool",
    "DeWalt Drywall",
    "Milwaukee Drywall",
    "Makita Drywall",
    "Senco Drywall",
    
    // Flooring Tools
    "Roberts",
    "QEP",
    "Crain",
    "Taylor Tools",
    "Kraft Tool",
    "Bon Tool",
    "Marshalltown",
    "Rubi",
    "Montolit",
    "Sigma",
    "DeWalt Tile",
    "MK Diamond",
    "Husqvarna Tile",
    "iQ Power Tools",
    "Bona",
    "Norton Floor",
    "Lagler",
    "Clarke Floor",
    "American Sanders",
    "Galaxy Floor Machines",
    
    // Painting & Finishing
    "Graco",
    "Wagner",
    "Titan",
    "Fuji Spray",
    "Kremlin Rexson",
    "DeVilbiss",
    "SATA",
    "Iwata",
    "Purdy",
    "Wooster",
    "Corona",
    "Sherwin-Williams",
    "Benjamin Moore",
    "PPG",
    "Behr",
    "Valspar",
    "Dulux",
    "Rust-Oleum",
    "Minwax",
    "Varathane",
    "General Finishes",
    "Old Masters",
    "Zinsser",
    "Kilz",
    "3M Painting",
    "Frog Tape",
    "ScotchBlue",
    
    // Ladders & Scaffolding
    "Werner",
    "Louisville Ladder",
    "Little Giant",
    "Gorilla Ladders",
    "DeWalt Ladders",
    "Keller",
    "Metaltech",
    "Perry Scaffold",
    "Bil-Jax",
    "Waco",
    "Safway",
    "Scaffold America",
    "Upright Scaffolding",
    "Aluma Systems",
    "PERI",
    "Doka",
    "Acrow",
    "Layher",
    "Haki",
    
    // Safety Equipment
    "3M Safety",
    "Honeywell Safety",
    "MSA Safety",
    "Uvex",
    "Pyramex",
    "Ergodyne",
    "Klein Safety",
    "Milwaukee Safety",
    "DeWalt Safety",
    "Carhartt Workwear",
    "Dickies",
    "Caterpillar Workwear",
    "Timberland Pro",
    "Red Wing",
    "Wolverine",
    "Thorogood",
    "Irish Setter",
    "Keen Utility",
    "Ariat Work",
    "Danner",
    
    // Construction Materials
    "CertainTeed",
    "Owens Corning",
    "Johns Manville",
    "Rockwool",
    "Dow",
    "Kingspan",
    "Georgia-Pacific",
    "Weyerhaeuser",
    "Louisiana-Pacific",
    "Boise Cascade",
    "James Hardie",
    "Trex",
    "Azek",
    "TimberTech",
    "Fiberon",
    "Deckorators",
    "Simpson Strong-Tie",
    "USP Structural",
    "Mitek",
    
    // Other
    "Other"
  ],

  "Leisure & Activities": [
    // Camping & Hiking
    "Coleman",
    "The North Face",
    "Patagonia",
    "Columbia",
    "REI Co-op",
    "Osprey",
    "Gregory",
    "Deuter",
    "Kelty",
    "Big Agnes",
    "MSR",
    "Jetboil",
    "Snow Peak",
    "Sea to Summit",
    "Therm-a-Rest",
    "Nemo Equipment",
    "ENO (Eagles Nest Outfitters)",
    "Helinox",
    "Black Diamond",
    "Petzl",
    "Goal Zero",
    "BioLite",
    "Yeti",
    "RTIC",
    "Igloo",
    "Hydro Flask",
    "Stanley",
    "CamelBak",
    "Nalgene",
    "LifeStraw",
    "Sawyer",
    "Katadyn",
    "Garmin Outdoor",
    "Suunto",
    "Coros",
    
    // Travel & Luggage
    "Samsonite",
    "Tumi",
    "Rimowa",
    "Away",
    "Travelpro",
    "Briggs & Riley",
    "Delsey",
    "American Tourister",
    "Victorinox",
    "Swiss Gear",
    "Eagle Creek",
    "Osprey Luggage",
    "Patagonia Travel",
    "Peak Design",
    "Tortuga",
    "Nomatic",
    "Bellroy",
    "Cotopaxi",
    "Fjällräven",
    "Herschel",
    "JanSport",
    "Eastpak",
    "Kipling",
    "Longchamp",
    
    // Photography & Videography
    "Canon",
    "Nikon",
    "Sony",
    "Fujifilm",
    "Panasonic Lumix",
    "Olympus",
    "Leica",
    "Hasselblad",
    "GoPro",
    "DJI",
    "Insta360",
    "Ricoh (Theta)",
    "Blackmagic Design",
    "RED",
    "ARRI",
    "Zhiyun",
    "DJI Ronin",
    "Moza",
    "Feiyu",
    "Manfrotto",
    "Gitzo",
    "Benro",
    "Sirui",
    "Peak Design Camera",
    "Think Tank",
    "Lowepro",
    "Tenba",
    "ONA",
    "Billingham",
    "Domke",
    
    // Drones
    "DJI",
    "Autel Robotics",
    "Skydio",
    "Parrot",
    "Yuneec",
    "Holy Stone",
    "Potensic",
    "Ruko",
    "Hubsan",
    "Syma",
    "Fimi",
    "Xiaomi Drones",
    
    // Binoculars & Optics
    "Zeiss",
    "Leica",
    "Swarovski Optik",
    "Nikon Optics",
    "Canon Optics",
    "Vortex Optics",
    "Bushnell",
    "Celestron",
    "Meade",
    "Orion",
    "Sky-Watcher",
    "Leupold",
    "Steiner",
    "Athlon Optics",
    "Maven",
    "Kowa",
    
    // Fishing
    "Shimano Fishing",
    "Daiwa",
    "Penn",
    "Abu Garcia",
    "Lew's",
    "Okuma",
    "Pflueger",
    "Ugly Stik",
    "St. Croix",
    "G. Loomis",
    "Fenwick",
    "Orvis Fishing",
    "Sage",
    "Temple Fork Outfitters",
    "Ross Reels",
    "Lamson",
    "Simms",
    "Patagonia Fishing",
    "Costa",
    "Maui Jim",
    "Oakley Fishing",
    "Rapala",
    "Berkley",
    "Strike King",
    "Zoom",
    "Yamamoto",
    "Z-Man",
    
    // Boating & Water Sports
    "Yamaha Marine",
    "Mercury Marine",
    "Honda Marine",
    "Suzuki Marine",
    "Evinrude",
    "Johnson",
    "Tohatsu",
    "Sea-Doo",
    "Kawasaki Jet Ski",
    "Yamaha WaveRunner",
    "Minn Kota",
    "Motorguide",
    "Garmin Marine",
    "Lowrance",
    "Humminbird",
    "Raymarine",
    "Simrad",
    "Furuno",
    "Mustang Survival",
    "Stearns",
    "Onyx",
    "O'Brien",
    "HO Sports",
    "Ronix",
    "Liquid Force",
    "Hyperlite",
    "CWB",
    
    // Hunting
    "Browning",
    "Remington",
    "Winchester",
    "Ruger",
    "Smith & Wesson",
    "Glock",
    "Sig Sauer",
    "Springfield Armory",
    "Beretta",
    "Benelli",
    "Mossberg",
    "Savage Arms",
    "Weatherby",
    "Tikka",
    "Sako",
    "Kimber",
    "CZ-USA",
    "Henry Rifles",
    "Marlin",
    "Leupold",
    "Vortex",
    "Zeiss Hunting",
    "Swarovski Hunting",
    "Nightforce",
    "Aimpoint",
    "EOTech",
    "Trijicon",
    "Holosun",
    "Sitka Gear",
    "First Lite",
    "Kuiu",
    "Badlands",
    "Eberlestock",
    "Stone Glacier",
    "Mystery Ranch",
    
    // Board Games & Puzzles
    "Hasbro",
    "Mattel",
    "Ravensburger",
    "Asmodee",
    "Fantasy Flight Games",
    "Days of Wonder",
    "Catan Studio",
    "Z-Man Games",
    "Stonemaier Games",
    "Exploding Kittens",
    "Gamewright",
    "ThinkFun",
    "Melissa & Doug",
    "Buffalo Games",
    "White Mountain",
    "Springbok",
    "Cobble Hill",
    "Galison",
    "Mudpuppy",
    "Djeco",
    
    // Party & Entertainment
    "Bose",
    "JBL",
    "Sony",
    "Marshall",
    "Ultimate Ears",
    "Anker Soundcore",
    "Harman Kardon",
    "Bang & Olufsen",
    "Sonos",
    "Fujifilm Instax",
    "Polaroid",
    "Kodak",
    "Canon Selphy",
    "HP Sprocket",
    
    // Other
    "Other"
  ],

  "Food, Agriculture & Farming": [
    // Tractors & Farm Equipment
    "John Deere",
    "Case IH",
    "New Holland",
    "Massey Ferguson",
    "Kubota",
    "AGCO",
    "Fendt",
    "Deutz-Fahr",
    "Claas",
    "Valtra",
    "Same",
    "Landini",
    "McCormick",
    "Kioti",
    "Mahindra",
    "LS Tractor",
    "TYM",
    "Branson",
    "Yanmar",
    "Bobcat",
    "JCB Agriculture",
    "Caterpillar Agriculture",
    "Challenger",
    "Versatile",
    "AGCO Allis",
    "White",
    
    // Harvesting & Tillage
    "John Deere Harvesting",
    "Case IH Harvesting",
    "New Holland Harvesting",
    "Claas Harvesting",
    "AGCO Harvesting",
    "Gleaner",
    "Lexion",
    "MacDon",
    "Draper",
    "Geringhoff",
    "Olimac",
    "Capello",
    "John Deere Tillage",
    "Case IH Tillage",
    "Great Plains",
    "Kuhn",
    "Lemken",
    "Horsch",
    "Väderstad",
    "Amazone",
    "Kverneland",
    "Kongskilde",
    "Pöttinger",
    "Salford",
    "Sunflower",
    "Kinze",
    "Monosem",
    
    // Irrigation & Water
    "John Deere Irrigation",
    "Valley Irrigation",
    "Zimmatic",
    "Reinke",
    "T-L Irrigation",
    "Valmont",
    "Netafim",
    "Jain Irrigation",
    "Toro Irrigation",
    "Rain Bird",
    "Hunter Irrigation",
    "Nelson Irrigation",
    "Senninger",
    "Komet",
    "Lindsay",
    "Rivulis",
    
    // Livestock Equipment
    "Priefert",
    "Tarter",
    "Behlen",
    "Sioux Steel",
    "Gallagher",
    "Zareba",
    "Parmak",
    "Powerfields",
    "Patriot",
    "Kencove",
    "Ritchie",
    "Miraco",
    "Lely",
    "DeLaval",
    "GEA",
    "BouMatic",
    "Fullwood Packo",
    "Milkline",
    "Westfalia",
    
    // Seeds & Crop Science
    "Bayer Crop Science",
    "Syngenta",
    "Corteva Agriscience",
    "BASF Agricultural",
    "Monsanto",
    "Pioneer",
    "DuPont",
    "Dow AgroSciences",
    "FMC",
    "Nufarm",
    "ADAMA",
    "UPL",
    "Sumitomo Chemical",
    "Arysta LifeScience",
    "Gowan",
    "Helena",
    "Wilbur-Ellis",
    "Nutrien",
    "Mosaic",
    "CF Industries",
    "Yara",
    "Koch Fertilizer",
    "Simplot",
    
    // Farm Tools & Supplies
    "Stihl",
    "Husqvarna",
    "Echo",
    "Shindaiwa",
    "Redmax",
    "Chapin",
    "Solo",
    "Jacto",
    "Hardi",
    "Hypro",
    "TeeJet",
    "Banjo",
    "Ace Pumps",
    "Pacer Pumps",
    "Fimco",
    "Agri-Fab",
    "Brinly",
    "Ohio Steel",
    
    // Greenhouse & Hydroponics
    "Hydrofarm",
    "General Hydroponics",
    "Advanced Nutrients",
    "Fox Farm",
    "Botanicare",
    "Canna",
    "Grodan",
    "Rockwool",
    "Perlite",
    "Vermiculite",
    "Sun System",
    "Gavita",
    "Fluence",
    "Heliospectra",
    "Kind LED",
    "Spider Farmer",
    "Mars Hydro",
    "Vivosun",
    "AC Infinity",
    "Quest Dehumidifiers",
    "Anden",
    "Surna",
    "Argus Controls",
    "Priva",
    "Ridder",
    "Netafim Greenhouse",
    
    // Food Processing
    "Bühler",
    "GEA Group",
    "Alfa Laval",
    "SPX Flow",
    "JBT Corporation",
    "Marel",
    "Key Technology",
    "Tomra",
    "Ishida",
    "Heat and Control",
    "Urschel",
    "Biro",
    "Hobart Food Equipment",
    "Globe",
    "Berkel",
    "Bizerba",
    "Mettler Toledo",
    
    // Food Brands (if selling food products)
    "Organic Valley",
    "Horizon Organic",
    "Earthbound Farm",
    "Annie's",
    "Amy's Kitchen",
    "Nature's Path",
    "Bob's Red Mill",
    "King Arthur Flour",
    "Arrowhead Mills",
    "Eden Foods",
    "Lundberg",
    "Dr. Praeger's",
    "Field Roast",
    "Beyond Meat",
    "Impossible Foods",
    "Gardein",
    "Lightlife",
    "Tofurky",
    
    // Other
    "Other"
  ],

  "Vehicles Parts & Accessories": [
    // OEM Parts Brands
    "Toyota Genuine Parts",
    "Honda Genuine Parts",
    "Ford Motorcraft",
    "GM Genuine Parts",
    "ACDelco",
    "Mopar (Chrysler/Dodge/Jeep)",
    "BMW Genuine Parts",
    "Mercedes-Benz Genuine Parts",
    "Audi Genuine Parts",
    "Volkswagen Genuine Parts",
    "Nissan Genuine Parts",
    "Hyundai Genuine Parts",
    "Kia Genuine Parts",
    
    // Engine Parts
    "Bosch",
    "Denso",
    "NGK",
    "ACDelco",
    "Delphi",
    "Motorcraft",
    "Mahle",
    "Mann Filter",
    "K&N",
    "Fram",
    "Wix",
    "Baldwin Filters",
    "Donaldson",
    "Gates",
    "Continental",
    "Dayco",
    "Fel-Pro",
    "Victor Reinz",
    "Clevite",
    "King Engine Bearings",
    "ACL",
    "Hastings",
    "Sealed Power",
    "Melling",
    "Cloyes",
    "Comp Cams",
    "Edelbrock",
    "Holley",
    "MSD",
    "Accel",
    "Pertronix",
    
    // Brakes
    "Brembo",
    "Akebono",
    "EBC Brakes",
    "Hawk Performance",
    "StopTech",
    "Wilwood",
    "Raybestos",
    "Wagner",
    "Bosch Brakes",
    "ACDelco Brakes",
    "Centric",
    "Power Stop",
    "R1 Concepts",
    "DBA (Disc Brakes Australia)",
    "Bendix",
    "TRW",
    "ATE",
    
    // Suspension & Steering
    "Bilstein",
    "KYB",
    "Monroe",
    "Gabriel",
    "Rancho",
    "Fox Shocks",
    "King Shocks",
    "ICON Vehicle Dynamics",
    "Old Man Emu",
    "Eibach",
    "H&R",
    "Tein",
    "BC Racing",
    "Coilover Kits",
    "Moog",
    "TRW Steering",
    "Lemförder",
    "Meyle",
    "Febi Bilstein",
    "SKF",
    "Timken",
    "National",
    "Koyo",
    "NSK",
    "NTN",
    
    // Exhaust
    "Borla",
    "Flowmaster",
    "MagnaFlow",
    "MBRP",
    "Corsa",
    "Akrapovic",
    "Remus",
    "Scorpion",
    "Milltek",
    "Invidia",
    "HKS",
    "Tanabe",
    "Yoshimura",
    "Two Brothers",
    "Walker Exhaust",
    "AP Exhaust",
    "Dynomax",
    "Cherry Bomb",
    "Thrush",
    "Hooker",
    "Gibson",
    
    // Transmission & Drivetrain
    "AAMCO",
    "Jasper Engines",
    "Genuine Transmission",
    "Sonnax",
    "B&M",
    "TCI",
    "Hughes Performance",
    "Performance Automatic",
    "Tremec",
    "South Bend Clutch",
    "Exedy",
    "ACT",
    "Centerforce",
    "Sachs",
    "LUK",
    "Valeo",
    "Eaton",
    "Dana Spicer",
    "Yukon Gear",
    "G2 Axle & Gear",
    "Motive Gear",
    "Richmond Gear",
    "Auburn Gear",
    
    // Tires
    "Michelin",
    "Bridgestone",
    "Goodyear",
    "Continental",
    "Pirelli",
    "Dunlop",
    "Yokohama",
    "Toyo",
    "BFGoodrich",
    "Firestone",
    "Hankook",
    "Kumho",
    "Nexen",
    "Falken",
    "General Tire",
    "Cooper Tires",
    "Nitto",
    "Mickey Thompson",
    "Maxxis",
    "Kenda",
    "Federal",
    "Sumitomo",
    "Achilles",
    "Sailun",
    "Westlake",
    
    // Wheels & Rims
    "BBS",
    "Enkei",
    "Volk Racing",
    "Work Wheels",
    "Rays Engineering",
    "OZ Racing",
    "Rotiform",
    "HRE",
    "Forgiato",
    "Giovanna",
    "Savini",
    "Niche",
    "Fuel Off-Road",
    "Method Race Wheels",
    "American Racing",
    "KMC",
    "XD Series",
    "Moto Metal",
    "Hostile",
    "TIS",
    "Vision",
    "Raceline",
    "Black Rhino",
    "TSW",
    "Petrol",
    "Avant Garde",
    "Stance",
    "Rohana",
    "Ferrada",
    "Vossen",
    "ADV.1",
    
    // Lighting
    "Philips Automotive",
    "Osram",
    "Sylvania",
    "GE Automotive",
    "Hella",
    "KC HiLiTES",
    "Rigid Industries",
    "Baja Designs",
    "Vision X",
    "Morimoto",
    "Diode Dynamics",
    "Oracle Lighting",
    "AnzoUSA",
    "Spyder Auto",
    "PIAA",
    "Putco",
    "Lumen",
    "AlphaRex",
    "GTR Lighting",
    "Mopar Lighting",
    
    // Car Audio & Electronics
    "Pioneer",
    "Kenwood",
    "Alpine",
    "JBL Car Audio",
    "Sony Car Audio",
    "JVC",
    "Rockford Fosgate",
    "Kicker",
    "MTX Audio",
    "Infinity",
    "Focal",
    "Hertz",
    "Audison",
    "Morel",
    "DD Audio",
    "Sundown Audio",
    "Skar Audio",
    "Memphis Audio",
    "DS18",
    "CT Sounds",
    "Boss Audio",
    "Dual",
    "Jensen",
    "Clarion",
    "Nakamichi",
    "McIntosh Car Audio",
    "Garmin Automotive",
    "TomTom",
    "Rand McNally",
    "Cobra",
    "Escort",
    "Valentine One",
    "Uniden",
    "Thinkware",
    "BlackVue",
    "Viofo",
    "Rexing",
    "Vantrue",
    "Nextbase",
    
    // Interior Accessories
    "WeatherTech",
    "Husky Liners",
    "3D MAXpider",
    "Lloyd Mats",
    "Covercraft",
    "Coverking",
    "CalTrend",
    "Katzkin",
    "Wet Okole",
    "Lund",
    "AVS",
    "Ventshade",
    "Wade",
    "Bushwacker",
    "EGR",
    
    // Exterior Accessories
    "Thule",
    "Yakima",
    "Rhino-Rack",
    "Curt Manufacturing",
    "Draw-Tite",
    "Reese",
    "B&W Trailer Hitches",
    "WeatherTech",
    "Lund",
    "AVS",
    "EGR",
    "Bushwacker",
    "Air Lift",
    "Firestone Ride-Rite",
    "Hellwig",
    "SuperSprings",
    "Roadmaster",
    "Blue Ox",
    
    // Performance Parts
    "APR",
    "Revo",
    "Cobb Tuning",
    "Dinan",
    "RennTech",
    "Brabus",
    "Hennessey",
    "Roush",
    "Shelby",
    "Saleen",
    "TRD (Toyota Racing Development)",
    "Mugen",
    "Nismo",
    "STI (Subaru Tecnica International)",
    "AMG",
    "M Performance",
    "S-Line",
    "RS",
    "Type R",
    "Vortech",
    "Procharger",
    "Whipple",
    "Kenne Bell",
    "Garrett",
    "BorgWarner",
    "Precision Turbo",
    "Turbonetics",
    "Forced Induction Labs",
    "Full Race",
    "Vibrant Performance",
    "Mishimoto",
    "Koyo Cooling",
    "CSF Radiators",
    "PWR",
    "Setrab",
    
    // Off-Road & 4x4
    "ARB",
    "Warn",
    "Smittybilt",
    "Rough Country",
    "Fabtech",
    "BDS Suspension",
    "Zone Offroad",
    "Pro Comp",
    "Superlift",
    "Skyjacker",
    "ReadyLIFT",
    "TeraFlex",
    "Rubicon Express",
    "Poison Spyder",
    "Metalcloak",
    "Rock Krawler",
    "JKS Manufacturing",
    "aFe Power",
    "Banks Power",
    "Sinister Diesel",
    "BD Diesel",
    "ATS Diesel",
    "Industrial Injection",
    "Fass Fuel Systems",
    "AirDog",
    "PPE",
    "Wehrli Custom Fab",
    "HSP Diesel",
    
    // Other
    "Other"
  ],

  "Jobs": [
    "Not Applicable"
  ],

  "Seeking Work CVs": [
    "Not Applicable"
  ],

  "Services": [
    "Not Applicable"
  ],

  // --- NEWLY ADDED CATEGORIES BELOW ---

  "Mobile & Tech Accessories": [
    // Chargers & Power
    "Anker",
    "Belkin",
    "Baseus",
    "Ugreen",
    "RavPower",
    "Aukey",
    "Spigen",
    "Mophie",
    "Otterbox",
    "Zagg",
    "Satechi",
    "Hyper",
    "Nomad",
    "Native Union",
    "Twelve South",
    "Apple",
    "Samsung",
    "Google",
    "OnePlus",
    "Xiaomi",
    "Huawei",
    "Realme",
    "Oppo",
    "Vivo",
    
    // Cases & Protection
    "Spigen",
    "Otterbox",
    "Lifeproof",
    "Casetify",
    "UAG (Urban Armor Gear)",
    "Ringke",
    "Caseology",
    "Supcase",
    "Poetic",
    "Ghostek",
    "Incipio",
    "Tech21",
    "Mous",
    "Pela Case",
    "Totallee",
    "Pitaka",
    "Latercase",
    "dbrand",
    "Slickwraps",
    
    // Screen Protectors
    "Zagg",
    "Spigen",
    "amFilm",
    "JETech",
    "ESR",
    "IQ Shield",
    "ArmorSuit",
    "Supershieldz",
    "LK",
    "TOCOL",
    "Ailun",
    "Whitestone Dome",
    
    // Earphones & Headphones
    "Apple (AirPods)",
    "Samsung (Galaxy Buds)",
    "Sony",
    "Bose",
    "Jabra",
    "Sennheiser",
    "Audio-Technica",
    "Beats by Dre",
    "JBL",
    "Anker Soundcore",
    "Skullcandy",
    "Jaybird",
    "Bang & Olufsen",
    "Master & Dynamic",
    "Shure",
    "1More",
    "SoundPeats",
    "Tozo",
    "QCY",
    "Edifier",
    "Fiio",
    "Moondrop",
    "KZ",
    "Tin HiFi",
    
    // Smartwatch Accessories
    "Apple Watch Bands",
    "Samsung Watch Bands",
    "Garmin Bands",
    "Fitbit Bands",
    "Spigen Smartwatch",
    "Ringke Smartwatch",
    "UAG Smartwatch",
    "Nomad Smartwatch",
    "Casetify Smartwatch",
    "Supcase Smartwatch",
    
    // Cables & Adapters
    "Anker",
    "Belkin",
    "Ugreen",
    "Baseus",
    "Native Union",
    "Nomad",
    "Amazon Basics",
    "Cable Matters",
    "StarTech",
    "Monoprice",
    "Apple Lightning",
    "USB-C",
    "Micro USB",
    
    // Car Mounts & Accessories
    "iOttie",
    "Belkin Car",
    "Anker Car",
    "Spigen Car",
    "Scosche",
    "WeatherTech CupFone",
    "RAM Mounts",
    "ProClip",
    "Quad Lock",
    "Rokform",
    "Peak Design Mobile",
    
    // Portable Power
    "Anker PowerCore",
    "Mophie Powerstation",
    "RavPower",
    "Aukey",
    "Belkin Portable",
    "Zendure",
    "Goal Zero",
    "BioLite",
    "Jackery",
    "EcoFlow",
    "Bluetti",
    
    // African Market Brands
    "Oraimo",
    "Tecno Accessories",
    "Infinix Accessories",
    "Itel Accessories",
    "Safaricom Accessories",
    "MTN Accessories",
    "Airtel Accessories",
    "New Age",
    "Amped",
    
    // Other
    "Other"
  ],

  "Watches, Jewelry & Accessories": [
    // Luxury Watches
    "Rolex",
    "Patek Philippe",
    "Audemars Piguet",
    "Vacheron Constantin",
    "A. Lange & Söhne",
    "Jaeger-LeCoultre",
    "IWC Schaffhausen",
    "Panerai",
    "Omega",
    "Cartier",
    "Breguet",
    "Blancpain",
    "Hublot",
    "Richard Mille",
    "Chopard",
    "Piaget",
    "Ulysse Nardin",
    "Girard-Perregaux",
    "Zenith",
    "Breitling",
    "Tudor",
    "Grand Seiko",
    "Glashutte Original",
    "Roger Dubuis",
    "MB&F",
    "Greubel Forsey",
    "F.P. Journe",
    "H. Moser & Cie",
    "Arnold & Son",
    "Franck Muller",
    "Jacob & Co",
    
    // Premium Watches
    "Tag Heuer",
    "Longines",
    "Tissot",
    "Oris",
    "Bell & Ross",
    "Baume & Mercier",
    "Maurice Lacroix",
    "Montblanc",
    "Rado",
    "Frederique Constant",
    "Raymond Weil",
    "Hamilton",
    "Mido",
    "Certina",
    "Ebel",
    "Movado",
    "Nomos Glashutte",
    "Sinn",
    "Junghans",
    "Muhle Glashutte",
    "Fortis",
    "Ball Watch",
    
    // Mid-Range Watches
    "Seiko",
    "Citizen",
    "Orient",
    "Bulova",
    "Victorinox Swiss Army",
    "Luminox",
    "Glycine",
    "Alpina",
    "Edox",
    "Eterna",
    "Zodiac",
    "Doxa",
    "Squale",
    "Christopher Ward",
    "Steinhart",
    "Dan Henry",
    "Baltic",
    "Lorier",
    "Farer",
    "Brew Watch Co",
    
    // Affordable Watches
    "Casio",
    "G-Shock",
    "Timex",
    "Fossil",
    "Skagen",
    "Michael Kors Watches",
    "Nixon",
    "MVMT",
    "Daniel Wellington",
    "Vincero",
    "Stuhrling",
    "Invicta",
    "Seiko 5",
    "Orient Bambino",
    "Vostok",
    "Swatch",
    
    // Smartwatches
    "Apple Watch",
    "Samsung Galaxy Watch",
    "Garmin",
    "Fitbit",
    "Amazfit",
    "Huawei Watch",
    "Xiaomi Mi Watch",
    "Suunto",
    "Polar",
    "Coros",
    "Withings",
    "Fossil Smartwatch",
    "Michael Kors Access",
    "Tag Heuer Connected",
    "Montblanc Summit",
    "Tissot T-Touch",
    "Citizen CZ Smart",
    "Casio Pro Trek",
    
    // Fine Jewelry - Luxury
    "Cartier",
    "Tiffany & Co",
    "Van Cleef & Arpels",
    "Harry Winston",
    "Bulgari",
    "Graff",
    "Chopard",
    "Piaget",
    "Boucheron",
    "Chaumet",
    "Mikimoto",
    "David Yurman",
    "Roberto Coin",
    "Marco Bicego",
    "Pomellato",
    "De Beers",
    "Hearts on Fire",
    "Tacori",
    "Verragio",
    "Simon G",
    "Neil Lane",
    
    // Fashion Jewelry & Accessories
    "Pandora",
    "Swarovski",
    "Kate Spade",
    "Kendra Scott",
    "Alex and Ani",
    "Brighton",
    "James Avery",
    "Silpada",
    "Gorjana",
    "BaubleBar",
    "Missoma",
    "Monica Vinader",
    "Mejuri",
    "Ana Luisa",
    "Astrid & Miyu",
    "Adornmonde",
    "Jenny Bird",
    "Uncommon James",
    "Rocksbox",
    
    // Luxury Fashion Brands (Accessories)
    "Gucci",
    "Louis Vuitton",
    "Hermès",
    "Prada",
    "Chanel",
    "Dior",
    "Fendi",
    "Versace",
    "Burberry",
    "Balenciaga",
    "Saint Laurent",
    "Givenchy",
    "Bottega Veneta",
    "Valentino",
    "Alexander McQueen",
    "Celine",
    "Loewe",
    "Off-White",
    "Balmain",
    
    // Premium Fashion Accessories
    "Coach",
    "Michael Kors",
    "Kate Spade",
    "Tory Burch",
    "Marc Jacobs",
    "Furla",
    "Longchamp",
    "MCM",
    "Mulberry",
    "Salvatore Ferragamo",
    "Tod's",
    "Jimmy Choo",
    "Stuart Weitzman",
    "Roger Vivier",
    "Manolo Blahnik",
    "Christian Louboutin",
    
    // Sunglasses
    "Ray-Ban",
    "Oakley",
    "Persol",
    "Maui Jim",
    "Costa Del Mar",
    "Oliver Peoples",
    "Tom Ford",
    "Gucci Eyewear",
    "Prada Eyewear",
    "Dior Eyewear",
    "Chanel Eyewear",
    "Versace Eyewear",
    "Dolce & Gabbana Eyewear",
    "Burberry Eyewear",
    "Carrera",
    "Arnette",
    "Spy Optic",
    "Smith Optics",
    "Quay Australia",
    "Le Specs",
    "Warby Parker",
    "Garrett Leight",
    "Moscot",
    "Randolph Engineering",
    "American Optical",
    
    // Belts
    "Hermes Belts",
    "Gucci Belts",
    "Louis Vuitton Belts",
    "Salvatore Ferragamo Belts",
    "Burberry Belts",
    "Prada Belts",
    "Versace Belts",
    "Fendi Belts",
    "Bottega Veneta Belts",
    "Montblanc Belts",
    "Tommy Hilfiger Belts",
    "Calvin Klein Belts",
    "Hugo Boss Belts",
    "Diesel Belts",
    "Allen Edmonds",
    "Johnston & Murphy",
    "Cole Haan",
    "Fossil Belts",
    "Timberland Belts",
    "Levi's Belts",
    
    // Wallets
    "Louis Vuitton Wallets",
    "Gucci Wallets",
    "Hermes Wallets",
    "Prada Wallets",
    "Burberry Wallets",
    "Fendi Wallets",
    "Bottega Veneta Wallets",
    "Saint Laurent Wallets",
    "Balenciaga Wallets",
    "Coach Wallets",
    "Michael Kors Wallets",
    "Kate Spade Wallets",
    "Tory Burch Wallets",
    "Marc Jacobs Wallets",
    "MCM Wallets",
    "Montblanc Wallets",
    "Bellroy",
    "Ridge Wallet",
    "Secrid",
    "Fossil Wallets",
    "Tommy Hilfiger Wallets",
    "Calvin Klein Wallets",
    "Timberland Wallets",
    "Herschel Wallets",
    
    // Bags & Briefcases
    "Louis Vuitton Bags",
    "Gucci Bags",
    "Hermes Bags (Birkin, Kelly)",
    "Chanel Bags",
    "Prada Bags",
    "Dior Bags",
    "Fendi Bags",
    "Bottega Veneta Bags",
    "Saint Laurent Bags",
    "Balenciaga Bags",
    "Celine Bags",
    "Loewe Bags",
    "Valentino Bags",
    "Givenchy Bags",
    "Coach Bags",
    "Michael Kors Bags",
    "Kate Spade Bags",
    "Tory Burch Bags",
    "Marc Jacobs Bags",
    "MCM Bags",
    "Longchamp Bags",
    "Mulberry Bags",
    "Furla Bags",
    "Tumi Bags",
    "Samsonite Bags",
    "Briggs & Riley",
    "Hartmann",
    "Rimowa",
    "Montblanc Bags",
    "Piquadro",
    "Knomo",
    
    // Scarves & Accessories
    "Hermes Scarves",
    "Gucci Scarves",
    "Louis Vuitton Scarves",
    "Burberry Scarves",
    "Chanel Scarves",
    "Dior Scarves",
    "Fendi Scarves",
    "Versace Scarves",
    "Alexander McQueen Scarves",
    "Loro Piana",
    "Johnstons of Elgin",
    "Barbour Scarves",
    
    // Other
    "Other"
  ],

  "Miscellaneous / Others": [
    "Generic",
    "Unbranded",
    "Handmade",
    "Custom Made",
    "Vintage",
    "Antique",
    "Unknown Brand",
    "Local Brand",
    "Imported",
    "Other"
  ],
};