// src/config/categories.js
const categories = [
  { name: "Phones & Tablets", icon: "📱" },
  { name: "Services", icon: "🛠️" },
  { name: "Jobs", icon: "💼" },
  { name: "Commercial Equipment & Tools", icon: "🛠️" },
  { name: "Sports & Outdoors", icon: "⚽" },
  { name: "Repair & Construction", icon: "🔧" },
  { name: "Beauty & Personal Care", icon: "💄" },
  { name: "Home, Furniture & Appliances", icon: "🏠" },
  { name: "Leisure & Activities", icon: "🎯" },
  { name: "Health & Fitness", icon: "🏋️" },
  { name: "Babies & Kids", icon: "👶" },
  { name: "Art & Collectibles", icon: "🎨" },
  { name: "Fashion", icon: "👗" },
  { name: "Books & Stationery", icon: "📚" },
  { name: "Vehicles", icon: "🚗" },
  { name: "Gaming", icon: "🎮" },
  { name: "Electronics", icon: "💻" },
  { name: "Property", icon: "🏡" },
  { name: "Vehicles Parts & Accessories", icon: "⚙️" },
  { name: "Food, Agriculture & Farming", icon: "🌾" },
  { name: "Toys & Games", icon: "🧸" },
  { name: "Seeking Work CVs", icon: "📄" },
  { name: "Musical Instruments", icon: "🎹" },
  { name: "Pets", icon: "🐶" },
  { name: "Computers & Laptops", icon: "💻" },
];

export default categories;