// src/config/featuresByCategory.js - EXPANDED ENTERPRISE FEATURES
export const featuresByCategory = {

  "Phones & Tablets": [
    // Connectivity
    "5G Support",
    "4G LTE",
    "3G",
    "Wi-Fi 6 (802.11ax)",
    "Wi-Fi 5 (802.11ac)",
    "Bluetooth 5.0+",
    "NFC",
    "USB Type-C",
    "USB 3.0+",
    "Infrared (IR Blaster)",
    "Satellite Connectivity",
    // Display
    "AMOLED Display",
    "OLED Display",
    "LCD Display",
    "120Hz Refresh Rate",
    "90Hz Refresh Rate",
    "60Hz Refresh Rate",
    "4K Display",
    "QHD+ Display",
    "FHD+ Display",
    "HDR10+",
    "Dolby Vision",
    "Always On Display",
    "Notch Display",
    "Punch-hole Display",
    "Under-display Camera",
    "Foldable Display",
    "Curved Display",
    "Touchscreen",
    // Security
    "Face ID",
    "Fingerprint Sensor (In-display)",
    "Fingerprint Sensor (Side)",
    "Fingerprint Sensor (Rear)",
    "PIN / Pattern Lock",
    "Iris Scanner",
    // Camera
    "Triple Camera",
    "Quad Camera",
    "Dual Camera",
    "Single Camera",
    "Periscope Zoom",
    "Optical Zoom",
    "Digital Zoom",
    "Night Mode",
    "Camera Flash",
    "4K Video Recording",
    "8K Video Recording",
    "Slow Motion Video",
    "OIS (Optical Image Stabilization)",
    "EIS (Electronic Image Stabilization)",
    "Front Flash",
    "AI Camera",
    "Pro Camera Mode",
    // Battery & Charging
    "Fast Charging",
    "Wireless Charging",
    "Reverse Wireless Charging",
    "MagSafe Compatible",
    "Large Battery (5000mAh+)",
    "Solar Charging",
    // Storage & Memory
    "Expandable Storage (MicroSD)",
    "Dual SIM",
    "eSIM Support",
    // Build & Design
    "IP68 Dust/Water Resistant",
    "IP67 Dust/Water Resistant",
    "IP65 Dust Resistant",
    "Gorilla Glass",
    "Ceramic Back",
    "Titanium Frame",
    "Aluminum Frame",
    "Stainless Steel Frame",
    "Plastic Build",
    // Audio
    "Stereo Speakers",
    "Dolby Atmos Audio",
    "Hi-Res Audio",
    "3.5mm Headphone Jack",
    "Noise Cancellation",
    // Other Features
    "S Pen / Stylus",
    "Desktop Mode",
    "Game Mode",
    "AI Features",
    "DeX Mode (Samsung)",
    "Split Screen",
    "Kids Mode",
    "One-Hand Mode",
    "Dark Mode",
    "Flash Light",
    "FM Radio",
    "GPS",
    "Barometer",
    "Gyroscope",
    "Accelerometer",
    "Compass",
    "Heart Rate Sensor",
    "SpO2 Sensor",
    "Temperature Sensor"
  ],

  "Vehicles": [
    // Comfort & Interior
    "Air Conditioning",
    "Dual Zone Climate Control",
    "Heated Seats",
    "Ventilated Seats",
    "Leather Seats",
    "Fabric Seats",
    "Suede Seats",
    "Memory Seats",
    "Power Seats",
    "Massage Seats",
    "Panoramic Sunroof",
    "Sunroof / Moonroof",
    "Heated Steering Wheel",
    "Power Steering",
    "Tilt & Telescopic Steering",
    "Ambient Interior Lighting",
    "Heads-Up Display (HUD)",
    "Digital Instrument Cluster",
    "Analog Instrument Cluster",
    // Entertainment & Tech
    "Infotainment Screen",
    "Android Auto",
    "Apple CarPlay",
    "Built-in Navigation / GPS",
    "Bluetooth",
    "Wi-Fi Hotspot",
    "USB Ports",
    "Wireless Charging Pad",
    "Premium Sound System",
    "Bose Sound System",
    "Harman Kardon Sound System",
    "Bang & Olufsen Sound System",
    "JBL Sound System",
    "Meridian Sound System",
    "Mark Levinson Sound System",
    "Burmester Sound System",
    "Rear Entertainment Screen",
    "Digital Radio (DAB)",
    "CD / DVD Player",
    // Safety
    "ABS (Anti-lock Braking)",
    "EBD (Electronic Brake Distribution)",
    "ESC (Electronic Stability Control)",
    "Traction Control",
    "Airbags (Driver)",
    "Airbags (Passenger)",
    "Side Airbags",
    "Curtain Airbags",
    "Knee Airbags",
    "ISOFIX Child Seat Anchors",
    "Lane Departure Warning",
    "Lane Keep Assist",
    "Blind Spot Monitoring",
    "Rear Cross-Traffic Alert",
    "Forward Collision Warning",
    "Automatic Emergency Braking",
    "Pedestrian Detection",
    "Adaptive Cruise Control",
    "Cruise Control",
    "Parking Sensors (Front)",
    "Parking Sensors (Rear)",
    "360 Degree Camera",
    "Rear View Camera",
    "Surround View Camera",
    "Dashcam Included",
    "Tire Pressure Monitoring (TPMS)",
    "Night Vision",
    "Driver Drowsiness Alert",
    "Traffic Sign Recognition",
    "Speed Limiter",
    // Exterior
    "Alloy Wheels",
    "Keyless Entry",
    "Push Start Button",
    "Remote Start",
    "Power Tailgate",
    "Tow Bar",
    "Roof Rack",
    "Running Boards",
    "Xenon Headlights",
    "LED Headlights",
    "Adaptive Headlights",
    "Daytime Running Lights (DRL)",
    "Fog Lights",
    "Tinted Windows",
    "Privacy Glass",
    "Spare Tyre",
    "Run-Flat Tyres",
    // Performance
    "4WD / 4x4",
    "AWD (All Wheel Drive)",
    "FWD (Front Wheel Drive)",
    "RWD (Rear Wheel Drive)",
    "Low Range 4WD",
    "Locking Differential",
    "Air Suspension",
    "Adjustable Suspension",
    "Sport Mode",
    "Eco Mode",
    "Launch Control",
    "Paddle Shifters",
    "Manual Transmission",
    "Automatic Transmission",
    "CVT Transmission",
    "Turbo Charged",
    "Supercharged",
    "Intercooled",
    // Ownership
    "Full Service History",
    "One Owner",
    "Accident Free",
    "Warranty Remaining",
    "Road Worthy Certificate",
    "Imported",
    "Locally Assembled",
    "Low Mileage",
    "Brand New",
    "Foreign Used",
    "Locally Used"
  ],

  "Babies & Kids": [
    // Safety
    "Non-toxic Materials",
    "BPA Free",
    "Lead Free",
    "Phthalate Free",
    "CPSC Certified",
    "CE Certified",
    "EN71 Certified (Toy Safety)",
    "ASTM Certified",
    "Safety Harness",
    "Anti-tip Design",
    "Edge Protection",
    "Childproof Lock",
    "Flame Retardant",
    "Choking Hazard Free",
    // Usability
    "Washable",
    "Machine Washable",
    "Easy Clean",
    "Dishwasher Safe",
    "Portable",
    "Foldable",
    "Lightweight",
    "Compact",
    "Adjustable Height",
    "Adjustable Straps",
    "Reversible",
    "Multi-position",
    "Convertible",
    // Quality & Features
    "Durable",
    "Waterproof",
    "Breathable",
    "Hypoallergenic",
    "Organic Material",
    "Eco-Friendly",
    "Unisex",
    "Ergonomic Design",
    "Anti-bacterial",
    "UV Protection",
    "Noise Cancelling",
    "Soft Padded",
    // Baby Specific
    "Newborn Compatible",
    "Infant Compatible",
    "Toddler Compatible",
    "Anti-colic",
    "Self-sterilizing",
    "Temperature Indicator",
    "Smart Monitoring",
    "Night Light",
    "Soothing Sounds",
    "Lullaby Built-in",
    "Vibration Mode",
    "Rocking Motion",
    "Auto-swinging",
    "App Controlled",
    // Kids Toys Specific
    "Educational",
    "STEM Learning",
    "Creative Play",
    "Outdoor Play",
    "Indoor Play",
    "Age Appropriate",
    "Battery Included",
    "Batteries Not Required",
    "No Sharp Edges",
    "Soft Material",
    "Interactive",
    "Talking / Sound Effects",
    "Light Up",
    "Remote Controlled",
    "Complete Set"
  ],

  "Property": [
    // Basic Features
    "Balcony",
    "Terrace",
    "Garden",
    "Rooftop Access",
    "Courtyard",
    "Patio",
    // Parking & Access
    "Parking Space",
    "Covered Parking",
    "Garage",
    "Double Garage",
    "Electric Gate",
    "Intercom / Video Intercom",
    "Smart Doorbell",
    "Wheelchair Accessible",
    "Elevator / Lift",
    "Ramp Access",
    // Utilities
    "Generator (Full House)",
    "Generator (Shared)",
    "Solar Power",
    "Solar Water Heater",
    "Borehole Water",
    "Prepaid Meter",
    "Postpaid Meter",
    "Water Heater",
    "Gas Cooker Connection",
    "Internet Ready",
    "Fibre Optic Ready",
    "DSTV Connection Ready",
    // Security
    "Security System",
    "CCTV Cameras",
    "Gated Community",
    "24-Hour Security",
    "Panic Room",
    "Safe Room",
    "Electric Fence",
    "Guard House",
    "Biometric Access",
    // Interior Features
    "Furnished",
    "Semi-Furnished",
    "Unfurnished",
    "Wardrobes",
    "Built-in Wardrobes",
    "Walk-in Closet",
    "En-suite Bathroom",
    "Guest Toilet",
    "Domestic Staff Quarters",
    "Boys Quarters (BQ)",
    "Open Plan Kitchen",
    "Fitted Kitchen",
    "American Kitchen",
    "Breakfast Bar",
    "Pantry",
    "Fireplace",
    "High Ceilings",
    "Marble Floors",
    "Hardwood Floors",
    "Tiled Floors",
    "Carpeted Floors",
    "False Ceiling",
    "Air Conditioning (Central)",
    "Air Conditioning (Split Unit)",
    "Ceiling Fans",
    "Blinds / Curtains",
    // Outdoor / Community
    "Swimming Pool",
    "Children's Playground",
    "Gym / Fitness Center",
    "Basketball Court",
    "Tennis Court",
    "Club House",
    "Shopping Mall Nearby",
    "School Nearby",
    "Hospital Nearby",
    "Church / Mosque Nearby",
    "Market Nearby",
    // Property Type Features
    "Serviced",
    "Newly Built",
    "Renovated",
    "Corner Piece",
    "Waterfront",
    "Sea View",
    "City View",
    "Mountain View",
    "Quiet Neighborhood",
    "Close to Highway",
    "Flood Free Area",
    "Survey Plan Available",
    "C of O Available",
    "Governor's Consent",
    "Deed of Assignment",
    "Land Use Permit"
  ],

  "Electronics": [
    // Connectivity
    "Bluetooth",
    "Wi-Fi",
    "Wi-Fi 6",
    "NFC",
    "USB-A Port",
    "USB-C Port",
    "USB 3.0",
    "HDMI",
    "HDMI 2.1",
    "DisplayPort",
    "VGA",
    "Ethernet Port",
    "SD Card Slot",
    "Optical Audio",
    "AUX / 3.5mm Jack",
    "Thunderbolt",
    "Infrared",
    // Display & Visual
    "4K Resolution",
    "8K Resolution",
    "Full HD (1080p)",
    "HD Ready (720p)",
    "OLED Display",
    "QLED Display",
    "AMOLED",
    "IPS Panel",
    "120Hz Refresh Rate",
    "144Hz Refresh Rate",
    "HDR10",
    "HDR10+",
    "Dolby Vision",
    "Curved Screen",
    "Flat Screen",
    "Touchscreen",
    "Anti-Glare",
    // Audio
    "Stereo Sound",
    "Surround Sound",
    "Dolby Atmos",
    "DTS:X",
    "Hi-Res Audio",
    "Noise Cancellation",
    "Voice Control",
    "Built-in Microphone",
    "Built-in Speakers",
    // Smart Features
    "Smart Features",
    "Google TV",
    "Android TV",
    "Tizen OS (Samsung)",
    "webOS (LG)",
    "Amazon Fire OS",
    "Roku OS",
    "Apple TV",
    "Voice Assistant (Alexa)",
    "Voice Assistant (Google)",
    "Voice Assistant (Siri)",
    "Screen Mirroring",
    "Chromecast Built-in",
    "AirPlay Compatible",
    "App Store Access",
    // Power & Efficiency
    "Energy Star Rated",
    "Energy Efficient",
    "Auto Power Off",
    "Standby Mode",
    "Solar Compatible",
    "Inverter Compatible",
    // Other
    "Remote Control",
    "Warranty Included",
    "Waterproof / Splash Proof",
    "Portable",
    "Wall Mountable",
    "Rack Mountable",
    "Fan Cooled",
    "Fanless Design",
    "LED Indicator",
    "Digital Display",
    "Programmable",
    "Timer Function",
    "Child Lock",
    "Multi-voltage (100-240V)"
  ],

  "Beauty & Personal Care": [
    // Formulation
    "Organic",
    "Natural Ingredients",
    "Vegan",
    "Cruelty-Free",
    "Dermatologically Tested",
    "Hypoallergenic",
    "Fragrance-Free",
    "Paraben-Free",
    "Sulfate-Free",
    "Silicone-Free",
    "Alcohol-Free",
    "Dye-Free",
    "Mineral Oil Free",
    "Petroleum Free",
    "Phthalate-Free",
    "SLS Free",
    "Gluten-Free",
    "Formaldehyde Free",
    "Non-Comedogenic",
    "Oil-Free",
    "Water-Based",
    "Oil-Based",
    "pH Balanced",
    // Skin Benefits
    "Moisturizing",
    "Hydrating",
    "Anti-Aging",
    "Anti-Wrinkle",
    "Brightening",
    "Whitening",
    "Even Skin Tone",
    "SPF Protection",
    "Sun Protection",
    "Anti-Acne",
    "Pore Minimizing",
    "Exfoliating",
    "Nourishing",
    "Soothing",
    "Calming",
    "Firming",
    "Lifting",
    "Clarifying",
    "Detoxifying",
    "Antioxidant",
    "Anti-inflammatory",
    "Collagen Boosting",
    "Retinol",
    "Vitamin C",
    "Niacinamide",
    "Hyaluronic Acid",
    "Glycolic Acid",
    "Salicylic Acid",
    "Peptides",
    "AHA / BHA",
    // Hair Benefits
    "Strengthening",
    "Volumizing",
    "Smoothing",
    "Frizz Control",
    "Heat Protection",
    "Color Protection",
    "Color Safe",
    "Dandruff Control",
    "Scalp Care",
    "Deep Conditioning",
    "Keratin Treatment",
    "Argan Oil",
    "Coconut Oil",
    "Castor Oil",
    "Biotin",
    // Product Specific
    "Long Lasting",
    "Waterproof",
    "Sweat Proof",
    "Transfer Proof",
    "Full Coverage",
    "Medium Coverage",
    "Light Coverage",
    "Buildable Coverage",
    "Matte Finish",
    "Dewy Finish",
    "Satin Finish",
    "Glossy Finish",
    "Luminous Finish",
    "Sheer Finish",
    "Fast Drying",
    "Quick Absorbing",
    "Lightweight",
    "Non-Greasy",
    "Travel Size",
    "Refillable",
    "Recyclable Packaging",
    "Eco-Friendly Packaging",
    "Allergen Tested",
    "Ophthalmologist Tested",
    "Pediatrician Tested",
    "Made in France",
    "Made in Korea",
    "Made in Japan",
    "Imported"
  ],

  "Home, Furniture & Appliances": [
    // Energy & Environment
    "Energy Efficient",
    "Energy Star Rated",
    "A+++ Energy Rating",
    "A++ Energy Rating",
    "A+ Energy Rating",
    "Eco-Friendly",
    "Solar Compatible",
    "Inverter Ready",
    "Low Power Consumption",
    "Recyclable Materials",
    // Appliance Specific
    "Inverter Compressor",
    "Digital Display",
    "Digital Controls",
    "Touch Controls",
    "Smart Controls",
    "App Controlled",
    "Voice Controlled",
    "Wi-Fi Connected",
    "Bluetooth Connected",
    "Auto Defrost",
    "Self-Cleaning",
    "Anti-bacterial Filter",
    "HEPA Filter",
    "Water Filter",
    "Steam Function",
    "Quick Wash",
    "Delay Start",
    "Child Lock",
    "Timer Function",
    "Auto Shut-Off",
    "Overheat Protection",
    "Surge Protection",
    // Furniture Specific
    "Assembly Required",
    "No Assembly Required",
    "Flat Pack",
    "Ready Assembled",
    "Solid Wood",
    "Engineered Wood",
    "MDF",
    "Plywood",
    "Metal Frame",
    "Aluminum Frame",
    "Stainless Steel",
    "Tempered Glass",
    "Leather Upholstery",
    "Fabric Upholstery",
    "Velvet Upholstery",
    "Waterproof Upholstery",
    "Stain Resistant",
    "Scratch Resistant",
    "Anti-tip",
    "Wall Anchored",
    "Adjustable Shelves",
    "Soft Close Hinges",
    "Soft Close Drawers",
    "Push to Open",
    "Under-bed Storage",
    "Ottoman Storage",
    // General
    "Portable",
    "Foldable",
    "Stackable",
    "Lightweight",
    "Heavy-Duty",
    "Durable",
    "Adjustable",
    "Extendable",
    "Modular",
    "Convertible",
    "Multi-functional",
    "Compact Design",
    "Space Saving",
    "Indoor Use",
    "Outdoor Use",
    "Indoor / Outdoor",
    "Warranty Included",
    "Spare Parts Available",
    "Service Center Available"
  ],

  "Commercial Equipment & Tools": [
    // Power & Performance
    "Corded Electric",
    "Cordless (Battery Powered)",
    "Pneumatic (Air Powered)",
    "Hydraulic",
    "Petrol Powered",
    "Diesel Powered",
    "Industrial Grade",
    "Heavy-Duty",
    "High Torque",
    "Variable Speed",
    "Brushless Motor",
    "Brushed Motor",
    "High RPM",
    // Build & Durability
    "Durable",
    "All Metal Construction",
    "Aluminum Body",
    "Reinforced",
    "Rust Resistant",
    "Corrosion Resistant",
    "Heat Resistant",
    "Chemical Resistant",
    "Weatherproof",
    "IP Rated",
    "Dust Proof",
    "Dust Extraction Compatible",
    "Vibration Dampening",
    "Anti-Vibration",
    // Usability
    "Portable",
    "Compact Design",
    "Lightweight",
    "Easy to Use",
    "Multi-purpose",
    "Ergonomic Handle",
    "Soft Grip Handle",
    "LED Work Light",
    "Laser Guide",
    "Digital Display",
    "Electronic Brake",
    "Overload Protection",
    "Thermal Protection",
    // Safety
    "Safety Lock",
    "Safety Trigger",
    "Blade Guard",
    "Kickback Prevention",
    "CE Certified",
    "OSHA Compliant",
    "CSA Certified",
    "UL Listed",
    // Batteries & Accessories
    "Battery Included",
    "Charger Included",
    "Carrying Case Included",
    "Bits Included",
    "Blades Included",
    "Compatible with 18V Battery",
    "Compatible with 20V Battery",
    "Compatible with 40V Battery",
    "Fast Charging Battery",
    // Other
    "Warranty Included",
    "Spare Parts Available",
    "Service Center Available",
    "Made in Germany",
    "Made in Japan",
    "Made in USA",
    "Commercial Grade",
    "Professional Use",
    "DIY Use"
  ],

  "Fashion": [
    // Material
    "100% Cotton",
    "100% Polyester",
    "100% Wool",
    "100% Silk",
    "100% Linen",
    "100% Leather",
    "100% Suede",
    "Denim",
    "Cashmere",
    "Velvet",
    "Satin",
    "Chiffon",
    "Nylon",
    "Spandex / Lycra",
    "Fleece",
    "Sherpa",
    "Faux Leather",
    "Faux Fur",
    "Vegan Leather",
    "Organic Cotton",
    "Recycled Material",
    "Sustainable Fabric",
    "Blended Fabric",
    // Features
    "Waterproof",
    "Water Resistant",
    "Windproof",
    "Breathable",
    "Moisture Wicking",
    "Quick Dry",
    "Anti-UV",
    "UV Protection (UPF 50+)",
    "Stretchable",
    "4-Way Stretch",
    "Compression Fit",
    "Slim Fit",
    "Regular Fit",
    "Relaxed Fit",
    "Oversized",
    "True to Size",
    // Design
    "Handmade",
    "Hand Embroidered",
    "Hand Printed",
    "Limited Edition",
    "Exclusive Design",
    "Designer Piece",
    "Vintage Style",
    "Retro Style",
    "Classic Design",
    "Adjustable Size",
    "Reversible",
    "Unisex",
    "Maternity Friendly",
    "Plus Size Available",
    "Petite Size Available",
    // Footwear Specific
    "Non-Slip Sole",
    "Rubber Sole",
    "Leather Sole",
    "Memory Foam Insole",
    "Arch Support",
    "Padded Collar",
    "Waterproof Boots",
    "Steel Toe Cap",
    "Anti-Static",
    "Oil Resistant",
    // Care
    "Machine Washable",
    "Hand Wash Only",
    "Dry Clean Only",
    "Easy Iron",
    "Wrinkle Resistant",
    "Shrink Resistant",
    "Fade Resistant",
    "Color Fast",
    "Hypoallergenic",
    // Other
    "Brand New with Tags",
    "Brand New without Tags",
    "Authentic / Original",
    "Gift Box Included",
    "Certificate of Authenticity",
    "Imported",
    "Locally Made"
  ],

  "Food, Agriculture & Farming": [
    // Food Quality
    "Organic",
    "Certified Organic",
    "Non-GMO",
    "Non-GMO Verified",
    "Locally Sourced",
    "Farm Fresh",
    "Fresh",
    "Frozen",
    "Dried / Dehydrated",
    "Smoked",
    "Fermented",
    "Packaged",
    "Vacuum Sealed",
    "Refrigerated",
    "Shelf Stable",
    "No Preservatives",
    "No Artificial Colors",
    "No Artificial Flavors",
    "No Added Sugar",
    "Low Sodium",
    "Gluten-Free",
    "Dairy-Free",
    "Nut-Free",
    "Vegan",
    "Vegetarian",
    "Halal Certified",
    "Kosher Certified",
    "Fair Trade",
    "Rainforest Alliance",
    // Farming & Agriculture
    "Fertilizer Free",
    "Pesticide Free",
    "Chemical Free",
    "Free Range",
    "Grass Fed",
    "Pasture Raised",
    "Cage Free",
    "Hormone Free",
    "Antibiotic Free",
    "Heirloom Variety",
    "Hydroponic",
    "Aeroponic",
    "Aquaponic",
    "Biodynamic",
    "Permaculture",
    "Regenerative",
    "Sustainable Farming",
    "Indoor Grown",
    "Greenhouse Grown",
    "Open Field Grown",
    "Irrigated",
    "Rainfed",
    "Hand Harvested",
    "Machine Harvested",
    "Sun Dried",
    "Shade Dried",
    // Equipment Specific
    "Heavy-Duty",
    "Durable",
    "Low Maintenance",
    "Fuel Efficient",
    "GPS Enabled",
    "Auto-Steer",
    "Variable Rate Technology",
    "Precision Agriculture",
    "Remote Monitoring",
    "Warranty Included",
    "Service Center Available"
  ],

  "Leisure & Activities": [
    // Outdoor
    "Portable",
    "Lightweight",
    "Compact",
    "Foldable",
    "Packable",
    "Waterproof",
    "Water Resistant",
    "Weatherproof",
    "UV Protection",
    "Wind Resistant",
    "Snow Proof",
    "All Season",
    "Summer Use",
    "Winter Use",
    // Durability
    "Durable",
    "Heavy-Duty",
    "Scratch Resistant",
    "Impact Resistant",
    "Tear Resistant",
    "Abrasion Resistant",
    "Military Grade",
    // Features
    "Multi-purpose",
    "Eco-Friendly",
    "Rechargeable",
    "Solar Powered",
    "Battery Powered",
    "Hand Powered",
    "Wireless",
    "Bluetooth Connected",
    "App Controlled",
    "GPS Enabled",
    "Night Vision",
    "LED Lighting",
    "Anti-slip",
    "Non-slip Grip",
    "Quick Setup",
    "Tool-free Assembly",
    "Adjustable",
    "Telescoping",
    // Safety
    "Safety Certified",
    "CE Marked",
    "Impact Absorbing",
    "Reflective",
    "High Visibility",
    "Life Jacket Compatible",
    "Buoyant",
    "Retractable",
    // Specific Use
    "Beginner Friendly",
    "Professional Grade",
    "Competition Grade",
    "Kids Friendly",
    "Family Friendly",
    "Pet Friendly",
    "Travel Friendly",
    "Indoor Use",
    "Outdoor Use",
    "Beach Use",
    "Pool Use",
    "Mountain Use",
    "Camping Use",
    "Fishing Use",
    "Hunting Use",
    "Photography Use",
    "Videography Use"
  ],

  "Pets": [
    // Animal Health
    "Vaccinated",
    "Up-to-date Vaccinations",
    "Dewormed",
    "Flea Treated",
    "Tick Treated",
    "Microchipped",
    "Neutered / Spayed",
    "Health Certificate Available",
    "Vet Checked",
    "Vet Records Available",
    "Pedigree Papers",
    "Registered Breed",
    "KUSA Registered",
    "AKC Registered",
    "DNA Tested",
    // Temperament
    "Trained",
    "House Trained",
    "Potty Trained",
    "Crate Trained",
    "Leash Trained",
    "Obedience Trained",
    "Non-aggressive",
    "Friendly",
    "Family Friendly",
    "Child Friendly",
    "Good with Kids",
    "Good with Other Dogs",
    "Good with Cats",
    "Good with Other Pets",
    "Indoor Pet",
    "Outdoor Pet",
    "Indoor / Outdoor",
    "Apartment Friendly",
    "Guard Dog",
    "Lap Dog",
    "Active / Energetic",
    "Calm / Gentle",
    "Playful",
    "Affectionate",
    "Independent",
    "Loyal",
    // Pet Products
    "Pet-safe Material",
    "Non-toxic",
    "Chew Resistant",
    "Waterproof",
    "Machine Washable",
    "Eco-Friendly",
    "Organic",
    "Natural Ingredients",
    "No Artificial Additives",
    "Grain-Free",
    "Hypoallergenic",
    "Vet Approved",
    "Durable",
    "Adjustable",
    "Reflective",
    "GPS Tracker Compatible"
  ],

  "Jobs": [
    // Work Type
    "Full-time",
    "Part-time",
    "Contract",
    "Freelance",
    "Internship",
    "Apprenticeship",
    "Volunteer",
    "Seasonal",
    "Temporary",
    "Permanent",
    // Work Location
    "On-site",
    "Remote Work",
    "Hybrid (Remote & On-site)",
    "Work from Home",
    "Field Work",
    "Travel Required",
    // Benefits
    "Competitive Salary",
    "Negotiable Salary",
    "Commission Based",
    "Bonus / Incentives",
    "Health Insurance",
    "HMO",
    "Pension / Retirement Plan",
    "Paid Annual Leave",
    "Maternity / Paternity Leave",
    "Sick Leave",
    "Housing Allowance",
    "Transport Allowance",
    "Meal Allowance",
    "Clothing Allowance",
    "Company Vehicle",
    "Fuel Allowance",
    "Phone Allowance",
    "Laptop Provided",
    "Stock Options",
    "Equity",
    // Development
    "Training Provided",
    "Professional Development",
    "Career Growth",
    "Mentorship",
    "Study Leave",
    "Tuition Reimbursement",
    "Conference Allowance",
    // Work Environment
    "Flexible Hours",
    "Flexible Schedule",
    "Shift Work",
    "Night Shift",
    "Day Shift",
    "Weekend Work",
    "No Weekend Work",
    "Team Environment",
    "Fast-paced Environment",
    "Startup Culture",
    "Corporate Environment",
    "International Company",
    "Local Company",
    // Requirements
    "Entry Level Welcome",
    "Experience Required",
    "Degree Required",
    "No Degree Required",
    "NYSC Required",
    "NYSC Exemption Accepted",
    "Immediate Start",
    "Urgent Hire",
    "Background Check Required",
    "Drug Test Required"
  ],

  "Repair & Construction": [
    // Power & Operation
    "Corded Electric",
    "Cordless (Battery Powered)",
    "Pneumatic",
    "Hydraulic",
    "Petrol Powered",
    "Diesel Powered",
    "Manual Operation",
    // Performance
    "Heavy-Duty",
    "Industrial Grade",
    "Professional Grade",
    "High Torque",
    "Variable Speed",
    "High RPM",
    "Brushless Motor",
    "High Pressure",
    // Build Quality
    "Durable",
    "All Metal Construction",
    "Aluminum Body",
    "Cast Iron Body",
    "Reinforced",
    "Rust Resistant",
    "Corrosion Resistant",
    "Heat Resistant",
    "Chemical Resistant",
    "Weatherproof",
    "Dust Proof",
    "Waterproof",
    "IP Rated",
    // Safety
    "Safety Lock",
    "Anti-kickback",
    "Blade Guard",
    "Overload Protection",
    "Thermal Protection",
    "GFCI Protected",
    "CE Certified",
    "OSHA Compliant",
    "CSA Certified",
    "Safety Harness Compatible",
    "Arc Flash Protection",
    "Insulated",
    // Usability
    "Portable",
    "Compact",
    "Lightweight",
    "Ergonomic Design",
    "Soft Grip Handle",
    "Multi-purpose",
    "Easy to Use",
    "Tool-free Blade Change",
    "Tool-free Adjustment",
    "LED Work Light",
    "Laser Guide",
    "Depth Adjustment",
    "Angle Adjustment",
    "Bevel Adjustment",
    "Digital Display",
    "Level Indicator",
    "Dust Extraction Port",
    "Dust Bag Included",
    // Accessories Included
    "Carrying Case Included",
    "Battery Included",
    "Charger Included",
    "Blade Included",
    "Bit Set Included",
    "Manual Included",
    // Other
    "Warranty Included",
    "Spare Parts Available",
    "Service Center Available",
    "Made in Germany",
    "Made in Japan",
    "Made in USA",
    "Imported",
    "Locally Sourced"
  ],

  "Seeking Work CVs": [
    // Availability
    "Full-time Available",
    "Part-time Available",
    "Contract Available",
    "Freelance Available",
    "Remote Work",
    "Hybrid Available",
    "On-site Available",
    "Immediate Start",
    "Available in 2 Weeks",
    "Available in 1 Month",
    "Notice Period Required",
    // Experience
    "Entry Level",
    "1 - 2 Years Experience",
    "2 - 5 Years Experience",
    "5 - 10 Years Experience",
    "10+ Years Experience",
    "Fresh Graduate",
    "NYSC Member",
    "NYSC Completed",
    // Education
    "Degree Holder",
    "Masters Degree Holder",
    "PhD Holder",
    "HND Holder",
    "Diploma Holder",
    "Professional Certification",
    // Work Preferences
    "Open to Relocation",
    "No Relocation",
    "Local Only",
    "International Opportunities Welcome",
    "Travel Available",
    "No Travel",
    "Driver's License",
    "Own Vehicle",
    // Skills & Qualities
    "Team Player",
    "Self-motivated",
    "Detail Oriented",
    "Problem Solver",
    "Fast Learner",
    "Bilingual",
    "Multilingual",
    "Leadership Skills",
    "Project Management",
    "Microsoft Office Proficient",
    "Computer Literate",
    "References Available",
    "Portfolio Available",
    "Work Samples Available"
  ],

  "Services": [
    // Professionalism
    "Professional",
    "Certified",
    "Licensed",
    "Insured",
    "Bonded",
    "Registered Business",
    "CAC Registered",
    "Experienced",
    "Expert",
    "Award Winning",
    "Top Rated",
    // Response & Availability
    "24/7 Available",
    "Same Day Service",
    "Next Day Service",
    "Fast Response",
    "Emergency Service",
    "Weekends Available",
    "Public Holidays Available",
    "Online Booking",
    "Phone Booking",
    "Walk-in Available",
    // Service Features
    "Free Consultation",
    "Free Quote",
    "Free Inspection",
    "Free Delivery",
    "Home Delivery",
    "Pick-up Available",
    "Home Visit",
    "On-site Service",
    "Remote Service",
    "Online Service",
    "Mobile Service",
    // Quality Assurance
    "Satisfaction Guaranteed",
    "Money Back Guarantee",
    "Warranty on Work",
    "Guarantee on Parts",
    "No Fix No Pay",
    "Fixed Price",
    "Transparent Pricing",
    "No Hidden Fees",
    "Free Estimate",
    "Competitive Pricing",
    // Team
    "Solo Practitioner",
    "Small Team",
    "Large Team",
    "Trained Staff",
    "Background Checked Staff",
    "Uniformed Staff",
    "Multilingual Staff",
    // Special
    "Eco-Friendly",
    "Sustainable Practices",
    "Uses Quality Materials",
    "Original Parts",
    "References Available",
    "Portfolio Available",
    "Before & After Photos",
    "Client Testimonials"
  ],

  "Vehicles Parts & Accessories": [
    // Quality
    "OEM Quality",
    "Genuine OEM",
    "OE Replacement",
    "Aftermarket",
    "Performance Upgrade",
    "Race Grade",
    "Heavy-Duty",
    "Forged",
    "Billet",
    "Cast",
    "Stamped Steel",
    // Condition
    "Brand New",
    "New in Box",
    "Used - Good Condition",
    "Refurbished",
    "Remanufactured",
    "Rebuilt",
    // Compatibility
    "Universal Fit",
    "Direct Fit",
    "Vehicle Specific",
    "Easy Install",
    "Plug and Play",
    "No Modification Required",
    "Modification Required",
    "Professional Install Recommended",
    "DIY Install Possible",
    "Comes with Hardware",
    "Instructions Included",
    // Material
    "Stainless Steel",
    "Carbon Steel",
    "Aluminum",
    "Carbon Fiber",
    "High-Density Polyethylene",
    "ABS Plastic",
    "Rubber",
    "Ceramic",
    "Titanium",
    "Copper",
    "Cast Iron",
    // Performance
    "Improved Performance",
    "Better Fuel Economy",
    "Reduced Emissions",
    "Better Cooling",
    "Better Braking",
    "Better Handling",
    "Better Traction",
    "Corrosion Resistant",
    "Heat Resistant",
    "Chemical Resistant",
    "Longer Lifespan",
    "Low Maintenance",
    // Certification
    "ISO Certified",
    "TÜV Certified",
    "DOT Approved",
    "ECE Certified",
    "SABS Approved",
    "SON Certified",
    "NAFDAC Approved",
    // Other
    "Warranty Included",
    "Return Policy",
    "Authentic",
    "Certificate of Authenticity",
    "Imported",
    "Locally Made"
  ],

  "Books & Stationery": [
    // Book Format
    "Hardcover",
    "Paperback",
    "Spiral Bound",
    "Ring Bound",
    "Board Book",
    "Flip Book",
    "Pop-up Book",
    "Illustrated",
    "Full Color",
    "Black & White",
    "Large Print",
    "Bilingual",
    "Translated",
    "Annotated",
    "Revised Edition",
    "First Edition",
    "Limited Edition",
    "Signed Copy",
    "Ex-Library Copy",
    "International Edition",
    "US Edition",
    "UK Edition",
    // Book Condition
    "Brand New (Sealed)",
    "Brand New (Unsealed)",
    "Like New",
    "Very Good",
    "Good",
    "Acceptable",
    "No Highlighting",
    "No Writing",
    "No Stickers",
    "No Tears",
    "No Water Damage",
    "Spine Intact",
    // Stationery Features
    "Acid Free",
    "Bleed Resistant",
    "Smear Proof",
    "Waterproof Ink",
    "Erasable",
    "Refillable",
    "Eco-Friendly",
    "Recycled Paper",
    "FSC Certified Paper",
    "Premium Paper",
    "Dotted Pages",
    "Lined Pages",
    "Blank Pages",
    "Grid Pages",
    "Numbered Pages",
    "Index Tabs",
    "Ribbon Bookmark",
    "Elastic Closure",
    "Lay Flat Binding",
    "Pocket Inside",
    "Perforated Pages",
    "Moisture Resistant Cover",
    "Soft Cover",
    "Hard Cover",
    // Other
    "Bundle Available",
    "Set of Books",
    "Complete Series",
    "Textbook",
    "Study Guide",
    "Answer Key Included",
    "CD / DVD Included",
    "Online Access Code Included",
    "Imported",
    "Locally Published"
  ],

  "Musical Instruments": [
    // Condition
    "Brand New",
    "Like New",
    "Good Condition",
    "Professionally Set Up",
    "Freshly Serviced",
    "Recently Tuned",
    "Recently Restrung",
    "New Strings",
    "New Head (Drums)",
    "New Pads",
    "New Valves",
    "New Reeds",
    // Included Accessories
    "Gig Bag Included",
    "Hard Case Included",
    "Soft Case Included",
    "Strap Included",
    "Picks Included",
    "Strings Included",
    "Rosin Included",
    "Bow Included",
    "Mouthpiece Included",
    "Reeds Included",
    "Pedal Included",
    "Sustain Pedal Included",
    "Stand Included",
    "Music Stand Included",
    "With Amplifier",
    "With Cabinet",
    "With Power Supply",
    "With Cables",
    "With Manual",
    // Features
    "Professional Grade",
    "Student Grade",
    "Beginner Friendly",
    "Handcrafted",
    "Hand Made",
    "Solid Wood",
    "Laminate Wood",
    "All Solid",
    "Solid Top",
    "Spruce Top",
    "Cedar Top",
    "Mahogany Back & Sides",
    "Rosewood Fretboard",
    "Maple Fretboard",
    "Ebony Fretboard",
    "Bone Nut",
    "Tusq Nut",
    "Locking Tuners",
    "Floyd Rose Tremolo",
    "Bigsby Tremolo",
    "Active Pickups",
    "Passive Pickups",
    "Humbucker Pickups",
    "Single Coil Pickups",
    "Built-in Tuner",
    "Built-in Preamp",
    "Built-in Effects",
    "MIDI Compatible",
    "USB Connection",
    "Bluetooth",
    "Weighted Keys",
    "Semi-weighted Keys",
    "Graded Hammer Action",
    "Velocity Sensitive",
    "Aftertouch",
    "Polyphonic",
    "88 Keys",
    "76 Keys",
    "61 Keys",
    "49 Keys",
    "37 Keys",
    "25 Keys",
    // Other
    "Vintage",
    "Rare",
    "Limited Edition",
    "Discontinued Model",
    "Signed",
    "Certificate of Authenticity",
    "Imported",
    "Locally Made"
  ],

  "Sports & Outdoors": [
    // General
    "Brand New",
    "Like New",
    "Good Condition",
    "Professional Grade",
    "Competition Grade",
    "Amateur / Recreational",
    "Beginner Friendly",
    "Kids Version",
    // Fit & Size
    "Size Adjustable",
    "One Size Fits All",
    "True to Size",
    "Unisex",
    "Men's",
    "Women's",
    "Kids'",
    // Performance
    "Lightweight",
    "Ultra-lightweight",
    "Heavy-Duty",
    "Durable",
    "High Performance",
    "Aerodynamic",
    "Ergonomic",
    "Balanced",
    "Flexible",
    "Rigid",
    "Shock Absorbing",
    "Impact Resistant",
    "Anti-vibration",
    // Weather & Environment
    "Weatherproof",
    "Waterproof",
    "Water Resistant",
    "Windproof",
    "Quick Dry",
    "Moisture Wicking",
    "Breathable",
    "Anti-UV",
    "UV Protection (UPF 50+)",
    "Sun Protection",
    "Reflective",
    "High Visibility",
    "Night Use",
    "All Season",
    "Summer",
    "Winter",
    "Snow Compatible",
    "Rain Compatible",
    // Safety
    "Safety Certified",
    "CE Marked",
    "Anti-slip",
    "Non-slip Grip",
    "Non-slip Sole",
    "Padded",
    "Cushioned",
    "Protective",
    "Reinforced",
    "Impact Protection",
    "Helmeted",
    "Armored",
    "Buoyant",
    "Float",
    // Specific Use
    "Indoor",
    "Outdoor",
    "Water Use",
    "Pool Use",
    "Beach Use",
    "Mountain Use",
    "Trail Use",
    "Road Use",
    "Track Use",
    "Field Use",
    "Court Use",
    "Gym Use",
    // Tech Features
    "GPS Enabled",
    "Bluetooth Connected",
    "Heart Rate Monitor",
    "App Compatible",
    "Smart Sensors",
    "Rechargeable",
    "Solar Powered",
    "LED Lights",
    "Audio Compatible",
    // Accessories
    "Carry Bag Included",
    "Case Included",
    "Accessories Included",
    "Pump Included",
    "Batteries Included",
    "Charger Included",
    "Manual Included",
    "Warranty Included"
  ],

  "Computers & Laptops": [
    // Display
    "Full HD Display (1080p)",
    "QHD Display (1440p)",
    "4K Display (2160p)",
    "OLED Display",
    "IPS Panel",
    "TN Panel",
    "VA Panel",
    "120Hz Refresh Rate",
    "144Hz Refresh Rate",
    "165Hz Refresh Rate",
    "240Hz Refresh Rate",
    "360Hz Refresh Rate",
    "60Hz Refresh Rate",
    "HDR Display",
    "Dolby Vision",
    "Anti-glare Screen",
    "Glossy Screen",
    "Touch Screen",
    "Stylus Compatible",
    "Narrow Bezels",
    // Keyboard & Input
    "Backlit Keyboard",
    "RGB Backlit Keyboard",
    "Mechanical Keyboard",
    "Chiclet Keyboard",
    "Numpad",
    "Fingerprint Reader",
    "Face Recognition",
    "IR Camera",
    "Precision Touchpad",
    "Multi-touch Gesture",
    "Physical Privacy Shutter",
    // Storage
    "SSD Storage",
    "NVMe SSD",
    "SATA SSD",
    "HDD Storage",
    "Hybrid Drive (HDD + SSD)",
    "Dual Drive (HDD + SSD)",
    "Expandable Storage",
    "SD Card Slot",
    // Performance
    "Intel Core i3",
    "Intel Core i5",
    "Intel Core i7",
    "Intel Core i9",
    "Intel Core Ultra",
    "AMD Ryzen 3",
    "AMD Ryzen 5",
    "AMD Ryzen 7",
    "AMD Ryzen 9",
    "Apple M1",
    "Apple M2",
    "Apple M3",
    "Apple M4",
    "Dedicated Graphics",
    "Integrated Graphics",
    "NVIDIA GTX",
    "NVIDIA RTX",
    "AMD Radeon",
    "Gaming Ready",
    "Workstation Grade",
    "VR Ready",
    "AI Ready",
    // Software
    "Windows 11",
    "Windows 10",
    "macOS",
    "Chrome OS",
    "Linux",
    "Office Installed",
    "Microsoft 365 Included",
    "Antivirus Included",
    "No Bloatware",
    // Ports & Connectivity
    "USB-A Port",
    "USB-C Port",
    "Thunderbolt 4",
    "Thunderbolt 3",
    "HDMI Port",
    "DisplayPort",
    "SD Card Reader",
    "Ethernet Port",
    "3.5mm Audio Jack",
    "Wi-Fi 6 (802.11ax)",
    "Wi-Fi 5 (802.11ac)",
    "Bluetooth 5.0+",
    "4G LTE",
    "5G",
    // Battery & Power
    "Long Battery Life",
    "All-day Battery (10hr+)",
    "Fast Charging",
    "USB-C Charging",
    "MagSafe Charging",
    "Slim Power Adapter",
    // Build & Design
    "Lightweight (Under 1.5kg)",
    "Ultra-thin",
    "Premium Build",
    "Metal Body",
    "Aluminum Chassis",
    "Carbon Fiber",
    "Magnesium Alloy",
    "Military Grade (MIL-STD-810)",
    "Dust Resistant",
    "Water Resistant",
    "Spill Resistant",
    "360-degree Hinge",
    "2-in-1 Convertible",
    "Detachable Keyboard",
    // Audio
    "Stereo Speakers",
    "Harman Kardon Speakers",
    "Bang & Olufsen Speakers",
    "Bose Speakers",
    "Dolby Atmos Audio",
    "Noise Cancelling Microphone",
    "Dual Microphone Array",
    // Camera
    "1080p Webcam",
    "720p Webcam",
    "IR Webcam",
    "Pop-up Camera",
    // Other
    "Cooling Pad Compatible",
    "Docking Station Compatible",
    "eGPU Compatible",
    "Brand New",
    "Refurbished",
    "Warranty Included",
    "Upgrade Available"
  ],

  "Gaming": [
    // Console & Platform
    "PlayStation 5 (PS5)",
    "PlayStation 4 (PS4)",
    "Xbox Series X",
    "Xbox Series S",
    "Xbox One",
    "Nintendo Switch",
    "Nintendo Switch OLED",
    "Nintendo Switch Lite",
    "PC Gaming",
    "Mobile Gaming",
    "Handheld Gaming",
    "Retro Gaming",
    "VR Gaming",
    // Display & Visual
    "4K Gaming",
    "8K Gaming",
    "1440p Gaming",
    "1080p Gaming",
    "120Hz Support",
    "144Hz Support",
    "165Hz Support",
    "240Hz Support",
    "360Hz Support",
    "HDR Support",
    "HDR10",
    "HDR10+",
    "Dolby Vision",
    "G-Sync Compatible",
    "AMD FreeSync",
    "Variable Refresh Rate (VRR)",
    "High FPS",
    "Low Latency",
    "Ray Tracing",
    "DLSS Support",
    "FSR Support",
    "Anti-aliasing",
    // Performance
    "High FPS",
    "Low Input Lag",
    "Fast Response Time",
    "Overclockable",
    "Liquid Cooled",
    "Air Cooled",
    "Silent Mode",
    // Peripherals Features
    "RGB Lighting",
    "Per-key RGB",
    "Mechanical Keyboard",
    "Optical Switches",
    "Linear Switches",
    "Tactile Switches",
    "Clicky Switches",
    "Hot-swappable Switches",
    "N-key Rollover",
    "Anti-ghosting",
    "Wireless",
    "Wired",
    "Dual Mode (Wired & Wireless)",
    "Bluetooth",
    "2.4GHz Wireless",
    "Low Latency Wireless",
    "Rechargeable",
    "Long Battery Life",
    "Adjustable DPI",
    "High DPI (16000+)",
    "Adjustable Weight",
    "Adjustable Sensitivity",
    "Surround Sound",
    "7.1 Surround Sound",
    "Noise Cancelling Mic",
    "Detachable Mic",
    "Flip-to-Mute Mic",
    "LED Mute Indicator",
    "Memory Foam Ear Cups",
    "Leatherette Ear Cups",
    "Fabric Ear Cups",
    "Trigger Stops",
    "Customizable Buttons",
    "Programmable Buttons",
    "Macro Support",
    "Onboard Memory",
    "Software Customizable",
    "Hair Trigger",
    "Vibration Feedback",
    "Haptic Feedback",
    "Adaptive Triggers",
    // VR Specific
    "6DoF Tracking",
    "Inside-out Tracking",
    "Eye Tracking",
    "Hand Tracking",
    "Standalone (No PC Required)",
    "PC VR",
    "Console VR",
    "Wireless VR",
    "Tethered VR",
    // Streaming & Content Creation
    "4K Capture",
    "1080p Capture",
    "60fps Capture",
    "120fps Capture",
    "Live Streaming Ready",
    "Passthrough",
    "Low Latency Preview",
    "Plug and Play",
    "XLR Input",
    "3.5mm Input",
    // Other
    "Brand New",
    "Like New",
    "Good Condition",
    "Complete Set",
    "Games Included",
    "Controllers Included",
    "Headset Included",
    "Warranty Included"
  ],

  "Health & Fitness": [
    // Connectivity & Tracking
    "Bluetooth Connected",
    "Wi-Fi Connected",
    "App Compatible",
    "iOS Compatible",
    "Android Compatible",
    "GPS Tracking",
    "Heart Rate Monitor",
    "SpO2 Monitor",
    "Blood Pressure Monitor",
    "ECG / EKG",
    "Stress Monitor",
    "Sleep Tracker",
    "Sleep Stages",
    "Calorie Counter",
    "Step Counter",
    "Distance Tracker",
    "Altitude Tracker",
    "Temperature Sensor",
    "Hydration Reminder",
    "Menstrual Cycle Tracking",
    "Breathing Exercises",
    "Guided Workouts",
    "Training Plans",
    "Recovery Score",
    // Build & Comfort
    "Waterproof",
    "Water Resistant",
    "Sweat Proof",
    "Dustproof",
    "Shockproof",
    "Lightweight",
    "Comfortable",
    "Breathable",
    "Ergonomic",
    "Non-slip",
    "Anti-scratch",
    // Battery & Power
    "Long Battery Life",
    "Battery Long Life (7 days+)",
    "Fast Charging",
    "Wireless Charging",
    "Solar Charging",
    "Always-on Display",
    // Equipment Features
    "Adjustable Resistance",
    "Digital Resistance",
    "Magnetic Resistance",
    "Air Resistance",
    "Water Resistance",
    "Motorized",
    "Foldable",
    "Compact",
    "Heavy-Duty",
    "Commercial Grade",
    "Home Use",
    "Professional Use",
    "Multi-function",
    "Free Weights Compatible",
    "Cable Machine",
    "Pulley System",
    "Incline Adjustable",
    "Decline Adjustable",
    "Speed Adjustable",
    "Programmable Workouts",
    "LCD Display",
    "HD Display",
    "Tablet Holder",
    "Phone Holder",
    "Water Bottle Holder",
    "Fan Built-in",
    "Cooling Fan",
    "Heart Rate Handles",
    "Quiet Operation",
    "Low Noise",
    "Shock Absorbing",
    "Non-slip Surface",
    "Non-slip Feet",
    "Transport Wheels",
    "Easy Assembly",
    // Supplements
    "Protein Supplement",
    "Pre-workout",
    "Post-workout",
    "Creatine",
    "BCAAs",
    "Multivitamins",
    "Omega-3",
    "Plant-based",
    "Whey Protein",
    "Casein Protein",
    "Vegan Protein",
    "No Artificial Sweeteners",
    "Gluten-Free",
    "Lactose Free",
    "Sugar Free",
    "Third-Party Tested",
    "GMP Certified",
    "NSF Certified",
    "Informed Sport Certified",
    // Other
    "Warranty Included",
    "Assembly Required",
    "Assembly Service Available",
    "Spare Parts Available",
    "Service Center Available"
  ],

  "Art & Collectibles": [
    // Authenticity
    "Original",
    "Authentic",
    "Certificate of Authenticity",
    "Provenance Available",
    "Signed by Artist",
    "Numbered",
    "Limited Edition",
    "One of a Kind",
    "Artist Proof",
    "Archival Quality",
    "Museum Quality",
    "Gallery Quality",
    "Investment Grade",
    // Condition
    "Mint Condition",
    "Near Mint",
    "Very Fine",
    "Fine",
    "Very Good",
    "Good",
    "Poor",
    "Professionally Restored",
    "Professionally Framed",
    "Professionally Matted",
    "Unframed",
    "Framed",
    "Ready to Hang",
    "Canvas Stretched",
    "Canvas Unstretched",
    "Rolled",
    "Flat",
    // Art Medium
    "Oil Painting",
    "Acrylic Painting",
    "Watercolor",
    "Gouache",
    "Pastel",
    "Charcoal",
    "Graphite / Pencil",
    "Ink Drawing",
    "Mixed Media",
    "Collage",
    "Digital Art",
    "Photography",
    "Printmaking",
    "Etching",
    "Lithograph",
    "Screen Print",
    "Giclée Print",
    "Linocut",
    "Woodcut",
    "Sculpture",
    "Bronze",
    "Marble",
    "Resin",
    "Ceramic",
    "Porcelain",
    "Glass Art",
    "Mosaic",
    "Textile Art",
    "Tapestry",
    "Fiber Art",
    "Jewelry Art",
    "Metal Art",
    "Wood Art",
    "Paper Art",
    "Street Art",
    // Collectibles Specific
    "In Original Box",
    "Complete Set",
    "Rare",
    "Vintage",
    "Antique",
    "Retired",
    "Discontinued",
    "Chase Variant",
    "Exclusive",
    "Convention Exclusive",
    "Store Exclusive",
    "Pre-order Exclusive",
    "First Print",
    "First Edition",
    "Foil Cover",
    "Variant Cover",
    "Holographic",
    "Graded",
    "PSA Graded",
    "CGC Graded",
    "Beckett Graded",
    "Slabbed",
    "Raw (Ungraded)",
    // Packaging & Display
    "Display Case Included",
    "Stand Included",
    "Plinth Included",
    "Dust Cover",
    "UV Protected",
    "Temperature Controlled Storage",
    "Acid Free Storage",
    "Custom Packaging",
    "Gift Box",
    // Other
    "Imported",
    "Locally Made",
    "Custom Order Available",
    "Commissioned Piece",
    "Shipping Worldwide"
  ],

  "Toys & Games": [
    // Safety
    "Non-toxic",
    "Lead Free",
    "BPA Free",
    "Phthalate Free",
    "CE Certified",
    "ASTM Certified",
    "CPSC Certified",
    "EN71 Certified",
    "No Sharp Edges",
    "Choke Hazard Free",
    "Flame Retardant",
    "Age Appropriate",
    // Educational
    "Educational",
    "STEM Learning",
    "STEAM Learning",
    "Coding / Programming",
    "Math Skills",
    "Language Skills",
    "Science Learning",
    "Art & Creativity",
    "Problem Solving",
    "Critical Thinking",
    "Fine Motor Skills",
    "Gross Motor Skills",
    "Sensory Play",
    "Montessori Inspired",
    "Waldorf Inspired",
    // Features
    "Interactive",
    "Electronic",
    "Mechanical",
    "Remote Controlled",
    "App Controlled",
    "Bluetooth",
    "Wi-Fi",
    "Talking / Voice",
    "Sound Effects",
    "Light Up",
    "Music / Songs",
    "Video",
    "Augmented Reality (AR)",
    "Virtual Reality (VR)",
    "Artificial Intelligence (AI)",
    // Physical
    "Indoor",
    "Outdoor",
    "Indoor / Outdoor",
    "Waterproof",
    "Water Play",
    "Sand Play",
    "Buildable",
    "Stackable",
    "Magnetic",
    "Foldable",
    "Portable",
    "Compact",
    "Lightweight",
    "Heavy-Duty",
    "Large Size",
    "Life Size",
    // Completeness
    "Complete Set",
    "Collectible",
    "Series",
    "Expansion Pack",
    "Starter Set",
    "Deluxe Edition",
    "Limited Edition",
    "Special Edition",
    "In Original Box",
    "New in Box",
    "All Pieces Included",
    "Instructions Included",
    // Power
    "Battery Included",
    "Battery Required (Not Included)",
    "Batteries Not Required",
    "Rechargeable",
    "USB Rechargeable",
    "Solar Powered",
    "Wind-up",
    "Pull-back Action",
    // Other
    "Unisex",
    "Boys",
    "Girls",
    "1 Player",
    "2 Players",
    "Multiplayer",
    "Family Game",
    "Party Game",
    "Travel Size",
    "Gift Ready",
    "Gift Box Included",
    "Warranty Included",
    "Replacement Parts Available"
  ],

  // --- NEWLY ADDED CATEGORIES ---

  "Mobile & Tech Accessories": [
    // Charging
    "Fast Charging",
    "Super Fast Charging",
    "65W Charging",
    "45W Charging",
    "33W Charging",
    "25W Charging",
    "20W Charging",
    "18W Charging",
    "15W Wireless Charging",
    "10W Wireless Charging",
    "Wireless Charging",
    "MagSafe Compatible",
    "Qi Compatible",
    "Reverse Wireless Charging",
    "Multi-device Charging",
    "GaN Charger",
    "Solar Charging",
    // Cable
    "USB Type-C",
    "USB Type-A",
    "Micro USB",
    "Lightning (Apple)",
    "Braided Cable",
    "Tangle Free",
    "Nylon Braided",
    "Kevlar Reinforced",
    "Heavy Duty Cable",
    "Short Cable (30cm)",
    "Standard Cable (1m)",
    "Long Cable (2m)",
    "Long Cable (3m)",
    "Coiled Cable",
    "Right Angle Cable",
    "Retractable Cable",
    "2-in-1 Cable",
    "3-in-1 Cable",
    // Protection
    "Surge Protection",
    "Over-voltage Protection",
    "Over-current Protection",
    "Short Circuit Protection",
    "Over-temperature Protection",
    "Drop Proof",
    "Shockproof",
    "Scratch Resistant",
    "Waterproof",
    "Water Resistant",
    "Dustproof",
    "Military Grade (MIL-STD-810)",
    "360 Degree Protection",
    "Raised Bezels (Camera Protection)",
    "Raised Bezels (Screen Protection)",
    // Compatibility
    "Universal Fit",
    "iPhone Compatible",
    "Samsung Compatible",
    "Huawei Compatible",
    "Tecno Compatible",
    "Infinix Compatible",
    "All Android Compatible",
    // Case Features
    "Transparent / Clear",
    "Matte Finish",
    "Glossy Finish",
    "Slim Profile",
    "Card Holder",
    "Kickstand",
    "Wallet Case",
    "Flip Case",
    "Magnetic Case",
    "Ring Holder",
    "Grip Stand",
    "Biodegradable Material",
    "Eco-Friendly",
    // Audio
    "Active Noise Cancellation (ANC)",
    "Transparency Mode",
    "Spatial Audio",
    "Dolby Atmos",
    "Hi-Res Audio",
    "LDAC Codec",
    "aptX HD",
    "AAC Codec",
    "SBC Codec",
    "Wireless",
    "Wired",
    "True Wireless (TWS)",
    "Neckband Style",
    "Over-ear",
    "On-ear",
    "In-ear",
    "Open-ear",
    "Bone Conduction",
    "IPX4 Sweat Resistant",
    "IPX5 Waterproof",
    "IPX7 Waterproof",
    "Long Battery Life",
    "Fast Charge Case",
    "Wireless Charging Case",
    "Built-in Microphone",
    "Multi-point Connection",
    "Voice Assistant Compatible",
    // General
    "LED Indicator",
    "Compact Design",
    "Lightweight",
    "Portable",
    "Foldable",
    "Retractable",
    "Adjustable",
    "Magnetic",
    "Bluetooth",
    "Plug and Play",
    "App Compatible",
    "Warranty Included",
    "Brand New",
    "Imported",
    "Locally Available"
  ],

  "Watches, Jewelry & Accessories": [
    // Watch Features
    "Automatic Movement",
    "Mechanical Movement",
    "Quartz Movement",
    "Solar Powered",
    "Kinetic Movement",
    "Chronograph",
    "GMT Function",
    "World Time",
    "Day Date Display",
    "Date Display",
    "Moon Phase",
    "Perpetual Calendar",
    "Annual Calendar",
    "Tourbillon",
    "Minute Repeater",
    "Power Reserve Indicator",
    "Helium Escape Valve",
    "COSC Certified (Chronometer)",
    "Swiss Made",
    "Japanese Movement",
    "German Made",
    // Water Resistance
    "Water Resistant (30m)",
    "Water Resistant (50m)",
    "Water Resistant (100m)",
    "Diver's Watch (200m)",
    "Diver's Watch (300m)",
    "Deep Diver (600m+)",
    // Smartwatch Features
    "Heart Rate Monitor",
    "SpO2 Monitor",
    "Blood Pressure Monitor",
    "ECG / EKG",
    "Sleep Tracker",
    "GPS Built-in",
    "Compass",
    "Altimeter",
    "Barometer",
    "Gyroscope",
    "NFC Payments",
    "Contactless Payment",
    "LTE / eSIM",
    "Calls from Watch",
    "Notifications",
    "Fitness Tracking",
    "App Store",
    "Always-on Display",
    "Fall Detection",
    "Crash Detection",
    "Emergency SOS",
    "Long Battery Life",
    "Fast Charging",
    "Wireless Charging",
    "Interchangeable Straps",
    "Compatible with iPhone",
    "Compatible with Android",
    // Watch Materials
    "Stainless Steel Case",
    "Titanium Case",
    "Aluminum Case",
    "Carbon Fiber Case",
    "Ceramic Case",
    "Gold Case",
    "Rose Gold Case",
    "Platinum Case",
    "PVD Coated",
    "DLC Coated",
    "Sapphire Crystal Glass",
    "Mineral Crystal Glass",
    "Hardlex Crystal",
    "Anti-reflective Coating",
    "Leather Strap",
    "Genuine Leather Strap",
    "Crocodile Leather Strap",
    "Rubber / Silicone Strap",
    "Nylon Strap",
    "NATO Strap",
    "Metal Bracelet",
    "Mesh Bracelet",
    "Ceramic Bracelet",
    "Deployant Clasp",
    "Butterfly Clasp",
    "Pin Buckle",
    "Adjustable Strap",
    "Quick Release Strap",
    // Jewelry Features
    "Handmade",
    "Hand Crafted",
    "Hand Engraved",
    "Hand Stamped",
    "Hand Painted",
    "Custom Made",
    "Bespoke",
    "Personalized",
    "Engraving Available",
    "Name Plate",
    "Birthstone",
    "Initial Charm",
    // Jewelry Materials
    "Solid Gold (24K)",
    "Solid Gold (22K)",
    "Solid Gold (18K)",
    "Solid Gold (14K)",
    "Solid Gold (9K)",
    "Gold Plated",
    "Gold Filled",
    "Gold Vermeil",
    "Rose Gold",
    "White Gold",
    "Solid Silver (Sterling 925)",
    "Silver Plated",
    "Rhodium Plated",
    "Solid Platinum",
    "Titanium",
    "Stainless Steel",
    "Brass",
    "Copper",
    "Alloy",
    "Resin",
    "Wood",
    "Beads",
    "Fabric / Thread",
    // Stones & Gems
    "Diamond",
    "Lab Diamond",
    "Ruby",
    "Emerald",
    "Sapphire",
    "Pearl",
    "Freshwater Pearl",
    "Amethyst",
    "Topaz",
    "Opal",
    "Garnet",
    "Turquoise",
    "Obsidian",
    "Onyx",
    "Jade",
    "Coral",
    "Cubic Zirconia (CZ)",
    "Swarovski Crystals",
    "No Stones",
    // Quality & Authenticity
    "Hypoallergenic",
    "Nickel Free",
    "Lead Free",
    "Cadmium Free",
    "Anti-tarnish",
    "Anti-allergic",
    "Scratch Resistant",
    "Durable",
    "Authentic / Genuine",
    "Certificate of Authenticity",
    "Hallmarked",
    "GIA Certified",
    "IGI Certified",
    "AGS Certified",
    "Limited Edition",
    "Vintage",
    "Antique",
    "Collector's Item",
    // Bags Specific
    "Genuine Leather",
    "Full Grain Leather",
    "Top Grain Leather",
    "Coated Canvas",
    "Monogram Canvas",
    "Nylon",
    "Canvas",
    "Suede",
    "Faux Leather",
    "Vegan Leather",
    "Waterproof",
    "Water Resistant",
    "Dust Bag Included",
    "Authenticity Card",
    "Serial Number",
    "RFID Blocking",
    "Multiple Compartments",
    "Zip Closure",
    "Magnetic Closure",
    "Turnlock Closure",
    "Drawstring Closure",
    "Detachable Strap",
    "Adjustable Strap",
    "Crossbody Strap",
    "Shoulder Strap",
    "Hand Carry",
    "Backpack Style",
    "Tote Style",
    // Sunglasses
    "UV400 Protection",
    "100% UV Protection",
    "Polarized Lenses",
    "Photochromic Lenses",
    "Mirror Lenses",
    "Gradient Lenses",
    "Anti-reflective Coating",
    "Scratch Resistant Lenses",
    "Impact Resistant Lenses",
    "Prescription Ready",
    "Spring Hinges",
    "Acetate Frame",
    "Metal Frame",
    "TR90 Frame",
    "Titanium Frame",
    "Lightweight Frame",
    "Adjustable Nose Pads",
    "Case Included",
    "Cleaning Cloth Included",
    // Packaging
    "Gift Box Included",
    "Luxury Packaging",
    "Pouch Included",
    "Authenticity Card",
    "Imported",
    "Locally Made",
    "Warranty Included"
  ],

  "Miscellaneous / Others": [
    "Brand New",
    "Like New",
    "Good Condition",
    "Fair Condition",
    "For Parts",
    "Portable",
    "Lightweight",
    "Compact",
    "Foldable",
    "Durable",
    "Heavy-Duty",
    "Multi-purpose",
    "Eco-Friendly",
    "Recyclable",
    "Biodegradable",
    "Handmade",
    "Custom Made",
    "Limited Edition",
    "Rare",
    "Vintage",
    "Antique",
    "Collectible",
    "Imported",
    "Locally Made",
    "Warranty Included",
    "Complete Set",
    "Accessories Included",
    "Manual Included",
    "Gift Ready",
    "Gift Box Included",
    "Urgent Sale",
    "Price Negotiable",
    "Bundle Available",
    "Wholesale Available",
    "Bulk Order Available"
  ],
};