export const fieldOptions = {

  size: [
    // Standard Clothing
    "XXS",
    "XS",
    "S",
    "M",
    "L",
    "XL",
    "XXL",
    "3XL",
    "4XL",
    "5XL",
    // Numeric Sizes (Pants/Jeans)
    "28",
    "29",
    "30",
    "31",
    "32",
    "33",
    "34",
    "36",
    "38",
    "40",
    "42",
    "44",
    // Shoe Sizes
    "UK 3",
    "UK 4",
    "UK 5",
    "UK 6",
    "UK 7",
    "UK 8",
    "UK 9",
    "UK 10",
    "UK 11",
    "UK 12",
    "UK 13",
    "US 5",
    "US 6",
    "US 7",
    "US 8",
    "US 9",
    "US 10",
    "US 11",
    "US 12",
    "US 13",
    "EU 36",
    "EU 37",
    "EU 38",
    "EU 39",
    "EU 40",
    "EU 41",
    "EU 42",
    "EU 43",
    "EU 44",
    "EU 45",
    "EU 46",
    // One Size
    "One Size",
    "Free Size",
    "Other"
  ],

  age_range: [
    // Baby
    "0 - 3 Months",
    "3 - 6 Months",
    "6 - 9 Months",
    "9 - 12 Months",
    "12 - 18 Months",
    "18 - 24 Months",
    // Toddler
    "2 - 3 Years",
    "3 - 4 Years",
    "4 - 5 Years",
    // Kids
    "5 - 6 Years",
    "6 - 7 Years",
    "7 - 8 Years",
    "8 - 9 Years",
    "9 - 10 Years",
    "10 - 11 Years",
    "11 - 12 Years",
    // Teens
    "12 - 13 Years",
    "13 - 14 Years",
    "14 - 15 Years",
    "15 - 16 Years",
    "16 - 17 Years",
    "17 - 18 Years",
    // Adults
    "18 - 21 Years",
    "21 - 25 Years",
    "25 - 30 Years",
    "30 - 40 Years",
    "40 - 50 Years",
    "50 - 60 Years",
    "60+ Years",
    // General
    "All Ages",
    "Other"
  ],

  bedrooms: [
    "Studio / Bedsitter",
    "1 Bedroom",
    "2 Bedrooms",
    "3 Bedrooms",
    "4 Bedrooms",
    "5 Bedrooms",
    "6 Bedrooms",
    "7 Bedrooms",
    "8 Bedrooms",
    "9 Bedrooms",
    "10+ Bedrooms"
  ],

  bathrooms: [
    "1 Bathroom",
    "1.5 Bathrooms",
    "2 Bathrooms",
    "2.5 Bathrooms",
    "3 Bathrooms",
    "3.5 Bathrooms",
    "4 Bathrooms",
    "4.5 Bathrooms",
    "5 Bathrooms",
    "6+ Bathrooms"
  ],

  experience_level: [
    "No Experience (Fresh Graduate)",
    "Entry Level (0 - 1 Year)",
    "Junior (1 - 2 Years)",
    "Mid Level (2 - 4 Years)",
    "Senior (4 - 7 Years)",
    "Lead / Principal (7 - 10 Years)",
    "Expert / Director (10+ Years)",
    "Executive / C-Level"
  ],

  skills: [
    // Tech & Software
    "HTML / CSS",
    "JavaScript",
    "TypeScript",
    "React",
    "React Native",
    "Vue.js",
    "Angular",
    "Next.js",
    "Node.js",
    "Express.js",
    "Python",
    "Django",
    "Flask",
    "PHP",
    "Laravel",
    "Java",
    "Kotlin",
    "Swift",
    "Flutter",
    "Dart",
    "C",
    "C++",
    "C#",
    ".NET",
    "Ruby",
    "Ruby on Rails",
    "Go (Golang)",
    "Rust",
    "Scala",
    "R",
    "MATLAB",
    "SQL",
    "MySQL",
    "PostgreSQL",
    "MongoDB",
    "Firebase",
    "Redis",
    "GraphQL",
    "REST APIs",
    "Docker",
    "Kubernetes",
    "AWS",
    "Azure",
    "Google Cloud",
    "DevOps",
    "CI/CD",
    "Linux",
    "Bash / Shell Scripting",
    "Git / GitHub",
    "Cybersecurity",
    "Ethical Hacking",
    "Machine Learning",
    "Artificial Intelligence",
    "Data Science",
    "Data Analysis",
    "Power BI",
    "Tableau",
    "Excel / Spreadsheets",
    "Blockchain",
    "Web3",
    "Solidity",
    
    // Design & Creative
    "UI / UX Design",
    "Graphic Design",
    "Logo Design",
    "Motion Graphics",
    "3D Modeling",
    "Animation",
    "Video Editing",
    "Photography",
    "Videography",
    "Adobe Photoshop",
    "Adobe Illustrator",
    "Adobe Premiere Pro",
    "Adobe After Effects",
    "Figma",
    "Sketch",
    "InDesign",
    "Canva",
    "CorelDraw",
    "Interior Design",
    "Fashion Design",
    "Architecture",
    
    // Business & Marketing
    "Sales",
    "Marketing",
    "Digital Marketing",
    "Social Media Marketing",
    "Content Marketing",
    "Email Marketing",
    "SEO",
    "SEM / Google Ads",
    "Facebook / Instagram Ads",
    "Influencer Marketing",
    "Brand Management",
    "Product Management",
    "Project Management",
    "Business Development",
    "Market Research",
    "Customer Service",
    "Public Relations",
    "Event Management",
    "E-commerce",
    "Dropshipping",
    "Affiliate Marketing",
    "Copywriting",
    "Content Writing",
    "Blogging",
    "Ghostwriting",
    "Translation",
    "Proofreading",
    
    // Finance & Legal
    "Accounting",
    "Bookkeeping",
    "Auditing",
    "Financial Analysis",
    "Tax Preparation",
    "Investment Management",
    "Banking",
    "Insurance",
    "Legal Research",
    "Paralegal",
    "Contract Management",
    "Compliance",
    "Risk Management",
    "Payroll Management",
    "QuickBooks",
    "Sage Accounting",
    
    // Trades & Technical
    "Carpentry",
    "Plumbing",
    "Electrical Work",
    "Welding",
    "Painting & Decorating",
    "Masonry / Bricklaying",
    "Tiling",
    "Roofing",
    "Plastering",
    "Glazing",
    "HVAC / Air Conditioning",
    "Mechanical Engineering",
    "Civil Engineering",
    "Structural Engineering",
    "Quantity Surveying",
    "Land Surveying",
    "Auto Mechanics",
    "Auto Body Repair",
    "Motorcycle Repair",
    "Appliance Repair",
    "Electronics Repair",
    "Phone Repair",
    "Computer Repair",
    "Locksmith",
    "Solar Installation",
    "CCTV Installation",
    "Network Installation",
    
    // Healthcare
    "Nursing",
    "Midwifery",
    "Pharmacy",
    "Medical Laboratory",
    "Radiology",
    "Physiotherapy",
    "Occupational Therapy",
    "Dental Assistant",
    "Optometry",
    "Nutrition & Dietetics",
    "Mental Health Counseling",
    "Social Work",
    "First Aid",
    "Elderly Care",
    "Childcare",
    "Veterinary",
    
    // Hospitality & Lifestyle
    "Cooking / Chef",
    "Baking & Pastry",
    "Catering",
    "Bartending",
    "Hotel Management",
    "Tourism & Travel",
    "Cleaning & Housekeeping",
    "Laundry",
    "Tailoring & Sewing",
    "Hair Dressing",
    "Barbing",
    "Makeup & Beauty",
    "Nail Technician",
    "Massage Therapy",
    "Personal Training",
    "Yoga Instruction",
    "Dance",
    "Music Instruction",
    
    // Education & Admin
    "Teaching",
    "Tutoring",
    "Curriculum Development",
    "Training & Development",
    "Data Entry",
    "Typing",
    "Virtual Assistant",
    "Administrative Support",
    "Reception",
    "Human Resources",
    "Recruitment",
    "Office Management",
    
    // Logistics & Security
    "Driving",
    "Truck Driving",
    "Motorcycle Delivery",
    "Logistics & Supply Chain",
    "Warehouse Management",
    "Inventory Management",
    "Security Guard",
    "Armed Security",
    "Surveillance",
    "Crowd Control",
    
    // Other
    "Other"
  ],

  condition: [
    "Brand New (Sealed)",
    "Brand New (Open Box)",
    "Like New (Used Once)",
    "Excellent",
    "Very Good",
    "Good",
    "Fair",
    "Poor",
    "For Parts / Not Working"
  ],

  used_detail: [
    "Less than 1 Week",
    "1 - 2 Weeks",
    "2 - 4 Weeks",
    "1 - 3 Months",
    "3 - 6 Months",
    "6 - 12 Months",
    "1 - 2 Years",
    "2 - 3 Years",
    "3 - 5 Years",
    "More than 5 Years"
  ],

  ram: [
    "512MB",
    "1GB",
    "2GB",
    "3GB",
    "4GB",
    "6GB",
    "8GB",
    "10GB",
    "12GB",
    "16GB",
    "18GB",
    "24GB",
    "32GB",
    "48GB",
    "64GB",
    "128GB",
    "256GB",
    "Other"
  ],

  storage: [
    "4GB",
    "8GB",
    "16GB",
    "32GB",
    "64GB",
    "128GB",
    "256GB",
    "512GB",
    "1TB",
    "2TB",
    "4TB",
    "8TB",
    "16TB",
    "Other"
  ],

  sim: [
    "Single SIM (Nano)",
    "Single SIM (Micro)",
    "Single SIM (Standard)",
    "Dual SIM (Nano + Nano)",
    "Dual SIM (Nano + Micro)",
    "eSIM Only",
    "Single SIM + eSIM",
    "Dual SIM + eSIM",
    "Triple SIM",
    "Other"
  ],

  fuel_type: [
    // Traditional
    "Petrol",
    "Diesel",
    "LPG (Liquefied Petroleum Gas)",
    "CNG (Compressed Natural Gas)",
    // Electric & Hybrid
    "Electric",
    "Hybrid (Petrol / Electric)",
    "Hybrid (Diesel / Electric)",
    "Plug-in Hybrid (PHEV)",
    "Mild Hybrid (MHEV)",
    // Alternative
    "Hydrogen",
    "Ethanol (E85)",
    "Biodiesel",
    "Solar Assisted",
    // Other
    "Other"
  ],

  engine: [
    // Small Engines
    "0.6L",
    "0.8L",
    "1.0L",
    "1.1L",
    "1.2L",
    "1.3L",
    "1.4L",
    "1.5L",
    "1.6L",
    "1.7L",
    "1.8L",
    "1.9L",
    // Mid Range
    "2.0L",
    "2.1L",
    "2.2L",
    "2.3L",
    "2.4L",
    "2.5L",
    "2.6L",
    "2.7L",
    "2.8L",
    "2.9L",
    // Large Engines
    "3.0L",
    "3.2L",
    "3.5L",
    "3.6L",
    "3.8L",
    "4.0L",
    "4.2L",
    "4.4L",
    "4.5L",
    "4.6L",
    "4.7L",
    "4.8L",
    // Performance & Truck
    "5.0L",
    "5.2L",
    "5.4L",
    "5.5L",
    "5.7L",
    "6.0L",
    "6.2L",
    "6.4L",
    "6.7L",
    "7.0L",
    "7.3L",
    "8.0L+",
    // Electric
    "Electric (No Engine)",
    // Other
    "Other"
  ],

  year: [
    "2025",
    "2024",
    "2023",
    "2022",
    "2021",
    "2020",
    "2019",
    "2018",
    "2017",
    "2016",
    "2015",
    "2014",
    "2013",
    "2012",
    "2011",
    "2010",
    "2009",
    "2008",
    "2007",
    "2006",
    "2005",
    "2004",
    "2003",
    "2002",
    "2001",
    "2000",
    "1999",
    "1998",
    "1997",
    "1996",
    "1995",
    "1994",
    "1993",
    "1992",
    "1991",
    "1990",
    "1985 - 1989",
    "1980 - 1984",
    "1975 - 1979",
    "1970 - 1974",
    "Before 1970"
  ],

  color: [
    // Neutrals
    "Black",
    "White",
    "Off White",
    "Cream",
    "Ivory",
    "Beige",
    "Grey",
    "Light Grey",
    "Dark Grey",
    "Charcoal",
    // Metals
    "Silver",
    "Gold",
    "Rose Gold",
    "Bronze",
    "Copper",
    "Titanium",
    "Space Grey",
    "Midnight",
    "Starlight",
    // Blues
    "Blue",
    "Light Blue",
    "Sky Blue",
    "Navy Blue",
    "Royal Blue",
    "Cobalt Blue",
    "Teal",
    "Turquoise",
    "Aqua",
    "Cyan",
    // Greens
    "Green",
    "Light Green",
    "Dark Green",
    "Olive Green",
    "Mint Green",
    "Forest Green",
    "Sage Green",
    "Emerald",
    "Lime Green",
    // Reds & Pinks
    "Red",
    "Dark Red",
    "Crimson",
    "Maroon",
    "Burgundy",
    "Wine Red",
    "Pink",
    "Light Pink",
    "Hot Pink",
    "Rose",
    "Coral",
    "Salmon",
    "Magenta",
    "Fuchsia",
    // Yellows & Oranges
    "Yellow",
    "Light Yellow",
    "Golden Yellow",
    "Mustard",
    "Orange",
    "Dark Orange",
    "Amber",
    "Peach",
    "Apricot",
    // Purples
    "Purple",
    "Light Purple",
    "Lavender",
    "Violet",
    "Indigo",
    "Lilac",
    "Mauve",
    "Plum",
    // Browns
    "Brown",
    "Light Brown",
    "Dark Brown",
    "Tan",
    "Camel",
    "Khaki",
    "Nude",
    "Mocha",
    "Chocolate",
    // Special
    "Multicolor",
    "Camouflage",
    "Tie-Dye",
    "Gradient",
    "Transparent",
    "Clear",
    "Other"
  ],

  brand: [
    // This is a general fallback brand list.
    // For specific categories, the brands.js file is used.
    "Apple",
    "Samsung",
    "Huawei",
    "Xiaomi",
    "Tecno",
    "Infinix",
    "Itel",
    "Nokia",
    "Sony",
    "LG",
    "HP",
    "Dell",
    "Lenovo",
    "Asus",
    "Acer",
    "Microsoft",
    "Google",
    "OnePlus",
    "Oppo",
    "Vivo",
    "Realme",
    "Honor",
    "Motorola",
    "Toyota",
    "Honda",
    "Ford",
    "BMW",
    "Mercedes-Benz",
    "Audi",
    "Volkswagen",
    "Nissan",
    "Hyundai",
    "Kia",
    "Lexus",
    "Mazda",
    "Subaru",
    "Mitsubishi",
    "Suzuki",
    "Peugeot",
    "Renault",
    "Volvo",
    "Tesla",
    "Nike",
    "Adidas",
    "Puma",
    "Reebok",
    "Under Armour",
    "New Balance",
    "Converse",
    "Vans",
    "Gucci",
    "Louis Vuitton",
    "Prada",
    "Chanel",
    "Zara",
    "H&M",
    "Uniqlo",
    "Levi's",
    "Tommy Hilfiger",
    "Ralph Lauren",
    "Calvin Klein",
    "Lacoste",
    "Hugo Boss",
    "IKEA",
    "Philips",
    "Bosch",
    "Whirlpool",
    "LG Electronics",
    "Samsung Electronics",
    "Panasonic",
    "Sharp",
    "Hisense",
    "TCL",
    "Bose",
    "JBL",
    "Canon",
    "Nikon",
    "Fujifilm",
    "GoPro",
    "DJI",
    "Anker",
    "Belkin",
    "Baseus",
    "Other"
  ],

  education: [
    "No Formal Education",
    "Primary School (FSLC)",
    "Junior Secondary School (JSS)",
    "Senior Secondary School / O-Level (WAEC / NECO)",
    "A-Level / IJMB / JUPEB",
    "Vocational / Technical Certificate",
    "National Diploma (ND)",
    "Higher National Diploma (HND)",
    "Bachelor's Degree (B.Sc / B.A / B.Eng / B.Ed)",
    "Postgraduate Diploma (PGD)",
    "Master's Degree (M.Sc / M.A / MBA / M.Eng)",
    "PhD / Doctorate",
    "Professional Certification (ICAN / ACCA / PMP / CFA etc.)",
    "Medical Degree (MBBS / MD)",
    "Law Degree (LLB / BL)",
    "Other"
  ],

  breed: [
    // Dogs - Popular
    "German Shepherd",
    "Labrador Retriever",
    "Golden Retriever",
    "Bulldog (English)",
    "French Bulldog",
    "Poodle",
    "Rottweiler",
    "Chihuahua",
    "Beagle",
    "Siberian Husky",
    "Alaskan Malamute",
    "Dachshund",
    "Doberman",
    "Boxer",
    "Great Dane",
    "Maltese",
    "Shih Tzu",
    "Yorkshire Terrier",
    "Pomeranian",
    "Bichon Frise",
    "Cocker Spaniel",
    "Springer Spaniel",
    "Border Collie",
    "Australian Shepherd",
    "German Pointer",
    "Weimaraner",
    "Vizsla",
    "Dalmatian",
    "Chow Chow",
    "Shar Pei",
    "Akita",
    "Shiba Inu",
    "Samoyed",
    "Bernese Mountain Dog",
    "Saint Bernard",
    "Newfoundland",
    "Mastiff",
    "Cane Corso",
    "Pit Bull Terrier",
    "American Staffordshire",
    "Bull Terrier",
    "Jack Russell Terrier",
    "West Highland Terrier",
    "Miniature Schnauzer",
    "Giant Schnauzer",
    "Lhasa Apso",
    "Cavalier King Charles Spaniel",
    "Basset Hound",
    "Bloodhound",
    "Greyhound",
    "Whippet",
    "Italian Greyhound",
    "Basenji",
    "Rhodesian Ridgeback",
    "Boerboel",
    "African Wild Dog",
    "Azawakh",
    "Africanis",
    
    // Cats
    "Persian",
    "Siamese",
    "Maine Coon",
    "British Shorthair",
    "Ragdoll",
    "Bengal",
    "Abyssinian",
    "Scottish Fold",
    "Russian Blue",
    "Sphynx",
    "Norwegian Forest Cat",
    "Siberian",
    "Burmese",
    "Birman",
    "Tonkinese",
    "Turkish Angora",
    "American Shorthair",
    "Devon Rex",
    "Cornish Rex",
    "Exotic Shorthair",
    "Oriental Shorthair",
    "Himalayan",
    "Munchkin",
    "Savannah",
    "Chausie",
    "Domestic Shorthair",
    "Domestic Longhair",
    
    // Birds
    "African Grey Parrot",
    "Amazon Parrot",
    "Macaw",
    "Cockatoo",
    "Cockatiel",
    "Budgerigar (Budgie)",
    "Lovebird",
    "Conure",
    "Eclectus",
    "Senegal Parrot",
    "Canary",
    "Finch",
    "Parakeet",
    "Pigeon",
    "Dove",
    "Mynah Bird",
    "Toucan",
    "Lorikeet",
    "Peafowl",
    "Ostrich",
    
    // Reptiles
    "Bearded Dragon",
    "Leopard Gecko",
    "Ball Python",
    "Corn Snake",
    "Blue Tongue Skink",
    "Chameleon",
    "Iguana",
    "Monitor Lizard",
    "Red-Eared Slider (Turtle)",
    "Tortoise",
    "Crested Gecko",
    "Axolotl",
    
    // Small Animals
    "Rabbit",
    "Guinea Pig",
    "Hamster (Syrian)",
    "Hamster (Dwarf)",
    "Gerbil",
    "Rat",
    "Mouse",
    "Chinchilla",
    "Ferret",
    "Hedgehog",
    "Sugar Glider",
    "Degu",
    
    // Fish
    "Goldfish",
    "Betta Fish",
    "Guppy",
    "Koi",
    "Oscar",
    "Cichlid",
    "Discus",
    "Angelfish",
    "Clownfish",
    "Arowana",
    "Catfish",
    "Pleco",
    "Tetra",
    "Molly",
    "Swordtail",
    "Rainbow Fish",
    "Puffer Fish",
    
    // Farm Animals
    "Cow",
    "Goat",
    "Sheep",
    "Pig",
    "Chicken",
    "Turkey",
    "Duck",
    "Goose",
    "Horse",
    "Donkey",
    "Camel",
    "Rabbit (Farm)",
    "Snail (Giant African)",
    "Grasscutter",
    "Catfish (Farm)",
    "Tilapia (Farm)",
    
    // Mixed / Other
    "Mixed Breed (Dog)",
    "Mixed Breed (Cat)",
    "Mixed Breed (Other)",
    "Not Sure",
    "Other"
  ],

  model: [],
  // NOTE: "model" is left empty intentionally.
  // It is a free-text field in your form (user types it manually).
  // No dropdown options needed.
};