// src/config/locationsByState.js - FIXED & COMPLETE
export const locationsByState = {
  Abia: ["Aba", "Umuahia", "Ohafia", "Bende", "Isuikwuato", "Arochukwu", "Ugwunagbo"],
  Adamawa: ["Yola", "Mubi", "Numan", "Ganye", "Demsa", "Maiha", "Hong"],
  "Akwa Ibom": ["Uyo", "Ikot Ekpene", "Eket", "Oron", "Abak", "Mkpat Enin", "Itu"],
  Anambra: ["Awka", "Onitsha", "Nnewi", "Okija", "Ogidi", "Ihiala", "Orumba"],
  Bauchi: ["Bauchi", "Azare", "Ningi", "Misau", "Jama'are", "Gamawa", "Dambam"],
  Bayelsa: ["Yenagoa", "Sagbama", "Nembe", "Ogbia", "Brass", "Ekeremor", "Kolokuma/Opokuma"],
  Benue: ["Makurdi", "Gboko", "Otukpo", "Vandeikya", "Katsina-Ala", "Ugba", "Konshisha"],
  Borno: ["Maiduguri", "Biu", "Damboa", "Bama", "Gwoza", "Monguno", "Askira/Uba"],
  "Cross River": ["Calabar", "Ikom", "Ogoja", "Obudu", "Etung", "Boki", "Akpabuyo"],
  Delta: ["Asaba", "Warri", "Sapele", "Ughelli", "Agbor", "Ozoro", "Oleh"],
  Ebonyi: ["Abakaliki", "Afikpo", "Ikwo", "Ezza", "Onicha", "Ohaukwu", "Ishielu"],
  Edo: ["Benin City", "Auchi", "Ekpoma", "Uromi", "Igueben", "Oredo", "Egor"],
  Ekiti: ["Ado-Ekiti", "Ikere", "Iyin", "Efon", "Oye", "Ilejemeje", "Omuo"],
  Enugu: ["Enugu", "Nsukka", "Awgu", "Agbani", "Udi", "Igbo-Eze", "Ezeagu"],
  Gombe: ["Gombe", "Kumo", "Billiri", "Yamaltu", "Funakaye", "Dukku", "Nafada"],
  Imo: ["Owerri", "Orlu", "Okigwe", "Mbaise", "Oguta", "Ohaji/Egbema", "Nkwerre"],
  Jigawa: ["Dutse", "Hadejia", "Kazaure", "Gumel", "Ringim", "Auyo", "Birni Kudu"],
  Kaduna: ["Kaduna", "Zaria", "Kafanchan", "Soba", "Kachia", "Giwa", "Kagarko"],
  Kano: ["Kano", "Wudil", "Rano", "Gaya", "Bichi", "Karaye", "Bunkure"],
  Katsina: ["Katsina", "Funtua", "Daura", "Kankara", "Malumfashi", "Dutsin-Ma", "Bakori"],
  Kebbi: ["Birnin Kebbi", "Argungu", "Yelwa", "Zuru", "Gwandu", "Sakaba", "Bagudo"],
  Kogi: ["Lokoja", "Okene", "Idah", "Ajaokuta", "Bassa", "Ankpa", "Egbeda"],
  Kwara: ["Ilorin", "Offa", "Omu-Aran", "Pategi", "Lafiagi", "Kaiama", "Baruten"],
  Lagos: ["Ikeja", "Lekki", "Victoria Island", "Surulere", "Yaba", "Ajah", "Ikorodu", "Epe"],
  Nasarawa: ["Lafia", "Awe", "Doma", "Keffi", "Nasarawa-Eggon", "Toto", "Wamba"],
  Niger: ["Minna", "Suleja", "Kontagora", "Bida", "Zungeru", "Lapai", "Chanchaga"],
  Ogun: ["Abeokuta", "Ijebu-Ode", "Sagamu", "Ilaro", "Ota", "Odogbolu", "Ewekoro"],
  Ondo: ["Akure", "Owo", "Ondo", "Ikare", "Okitipupa", "Ile-Oluji", "Odigbo"],
  Osun: ["Osogbo", "Ile-Ife", "Ede", "Ikirun", "Iwo", "Ife-East", "Olorunda"],
  Oyo: ["Ibadan", "Oyo", "Ogbomosho", "Iseyin", "Saki", "Olorunsogo", "Eruwa"],
  Plateau: ["Jos", "Pankshin", "Shendam", "Barkin Ladi", "Langtang", "Mangu", "Bassa"],
  Rivers: ["Port Harcourt", "Bonny", "Degema", "Eleme", "Obio/Akpor", "Ikwerre", "Okrika"],
  Sokoto: ["Sokoto", "Gwadabawa", "Tambuwal", "Wurno", "Binji", "Illela", "Rabah"],
  Taraba: ["Jalingo", "Wukari", "Lau", "Sardauna", "Takum", "Gashaka", "Yorro"],
  Yobe: ["Damaturu", "Gashua", "Potiskum", "Bade", "Fika", "Gujba", "Nguru"],
  Zamfara: ["Gusau", "Talata Mafara", "Bungudu", "Anka", "Maru", "Bakura", "Kaura Namoda"],
  FCT: ["Abuja", "Gwagwalada", "Kubwa", "Garki", "Maitama", "Asokoro", "Bwari"]
};