// src/config/nigerianStates.js
// Array of objects: { state: "State Name", cities: ["City1", "City2", ...] }

const nigerianStates = [
  { state: "Abia", cities: ["Aba", "Umuahia", "Ohafia", "Bende"] },
  { state: "Adamawa", cities: ["Yola", "Mubi", "Ganye", "Numan"] },
  { state: "Akwa Ibom", cities: ["Uyo", "Eket", "Ikot Ekpene", "Oron"] },
  { state: "Anambra", cities: ["Awka", "Onitsha", "Nnewi", "Otuocha"] },
  { state: "Bauchi", cities: ["Bauchi", "Azare", "Misau", "Toro"] },
  { state: "Bayelsa", cities: ["Yenagoa", "Sagbama", "Otuoke", "Brass"] },
  { state: "Benue", cities: ["Makurdi", "Gboko", "Vandeikya", "Otukpo"] },
  { state: "Borno", cities: ["Maiduguri", "Bama", "Gwoza", "Kaga"] },
  { state: "Cross River", cities: ["Calabar", "Ikom", "Ogoja", "Obudu"] },
  { state: "Delta", cities: ["Asaba", "Warri", "Sapele", "Ughelli"] },
  { state: "Ebonyi", cities: ["Abakaliki", "Afikpo", "Izzi", "Onueke"] },
  { state: "Edo", cities: ["Benin City", "Ekpoma", "Auchi", "Uromi"] },
  { state: "Ekiti", cities: ["Ado-Ekiti", "Ikere", "Omuo", "Ise-Ekiti"] },
  { state: "Enugu", cities: ["Enugu", "Nsukka", "Awgu", "Udi"] },
  { state: "Gombe", cities: ["Gombe", "Kaltungo", "Billiri", "Dukku"] },
  { state: "Imo", cities: ["Owerri", "Orlu", "Okigwe", "Oguta"] },
  { state: "Jigawa", cities: ["Dutse", "Hadejia", "Kafin Hausa", "Kiyawa"] },
  { state: "Kaduna", cities: ["Kaduna", "Zaria", "Kafanchan", "Soba"] },
  { state: "Kano", cities: ["Kano", "Wudil", "Gaya", "Bichi"] },
  { state: "Katsina", cities: ["Katsina", "Daura", "Funtua", "Bakori"] },
  { state: "Kebbi", cities: ["Birnin Kebbi", "Argungu", "Zuru", "Yauri"] },
  { state: "Kogi", cities: ["Lokoja", "Idah", "Okene", "Ajaokuta"] },
  { state: "Kwara", cities: ["Ilorin", "Offa", "Lokoja", "Omu-Aran"] },
  { state: "Lagos", cities: ["Lagos", "Ikeja", "Epe", "Ikorodu", "Lekki"] },
  { state: "Nasarawa", cities: ["Lafia", "Akwanga", "Keffi", "Nasarawa"] },
  { state: "Niger", cities: ["Minna", "Kontagora", "Suleja", "Bida"] },
  { state: "Ogun", cities: ["Abeokuta", "Ijebu-Ode", "Sagamu", "Ijebu Igbo"] },
  { state: "Ondo", cities: ["Akure", "Owo", "Ondo", "Ikare"] },
  { state: "Osun", cities: ["Osogbo", "Ilesa", "Ife", "Ede"] },
  { state: "Oyo", cities: ["Ibadan", "Oyo", "Ogbomosho", "Saki"] },
  { state: "Plateau", cities: ["Jos", "Bukuru", "Pankshin", "Shendam"] },
  { state: "Rivers", cities: ["Port Harcourt", "Bonny", "Obio-Akpor", "Degema"] },
  { state: "Sokoto", cities: ["Sokoto", "Gwadabawa", "Shagari", "Dange"] },
  { state: "Taraba", cities: ["Jalingo", "Wukari", "Gembu", "Bali"] },
  { state: "Yobe", cities: ["Damaturu", "Potiskum", "Gashua", "Buni Yadi"] },
  { state: "Zamfara", cities: ["Gusau", "Bungudu", "Talata Mafara", "Kaura Namoda"] },
  { state: "FCT", cities: ["Abuja", "Gwagwalada", "Kubwa", "Kwali"] },
];

export default nigerianStates;